const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fmt=n=>Intl.NumberFormat('en-IN').format(Math.round(n));
const nowTime=()=>new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});

const baseState={
  role:'organizer', logged:false, page:'command', scenario:'Normal Traffic', score:87,
  attendees:58420, inside:31840, incoming:7420, exiting:1430, warnings:3,
  gateNorth:72, gateEast:45, gateSouth:51, gateWest:38, parking:67, transport:63, hotel:71,
  tasks:[{id:1,title:'Deploy 3 additional shuttle buses',priority:'High',status:'Pending',from:'Organizer',pickup:'Parking P4',destination:'Unity Arena',capacity:180}],
  attendeeRoute:'Gate A', attendeeMessage:'Your recommended route is clear. Gate A estimated entry time: 9 min.',
  alerts:[
   {sev:'high',text:'Gate B crowd increasing faster than expected.',loc:'North Concourse',time:'2 min ago'},
   {sev:'medium',text:'Parking P2 has reached 84% capacity.',loc:'Parking P2',time:'4 min ago'},
   {sev:'info',text:'Metro East platform load returning to normal.',loc:'Metro East',time:'8 min ago'}],
  recommendations:[
    {id:'r1',title:'Predicted Congestion',loc:'North Gate',severity:'HIGH PRIORITY',current:72,predicted:91,action:'Redirect 700 arriving attendees toward East Gate.',impact:'North Gate 91% → 71%',approved:false},
    {id:'r2',title:'Transport Capacity Gap',loc:'Parking P4',severity:'HIGH PRIORITY',current:68,predicted:88,action:'Deploy 3 additional shuttle buses to Unity Arena.',impact:'Wait time 18 min → 8 min',approved:false},
    {id:'r3',title:'Parking Pressure',loc:'P2 / P4',severity:'MEDIUM',current:84,predicted:93,action:'Open Parking P4 overflow allocation.',impact:'P2 93% → 78%',approved:false}
  ]
};
let state={...baseState, ...(JSON.parse(localStorage.getItem('eventflow-state')||'{}'))};
const save=()=>localStorage.setItem('eventflow-state',JSON.stringify(state));

const icons={command:'◈',map:'⌖',crowd:'◉',transport:'⇄',hotel:'▤',parking:'▣',actions:'✦',alerts:'!',simulation:'◇',analytics:'⌁',timeline:'—',operators:'◎',settings:'⚙',overview:'◫',resources:'▦',assignments:'✓',forecast:'⌁',messages:'✉',journey:'➜',navigation:'⌁',event:'★',profile:'○'};
const navs={
 organizer:[['command','Command Center'],['map','Live Map'],['crowd','Crowd Intelligence'],['transport','Transport'],['hotel','Accommodation'],['parking','Parking'],['actions','AI Actions'],['alerts','Alerts'],['simulation','Simulation'],['analytics','Analytics'],['timeline','Event Timeline'],['operators','Operators'],['settings','Settings']],
 operator:[['overview','Overview'],['resources','Resources'],['assignments','Assignments'],['forecast','Demand Forecast'],['transport','Fleet / Capacity'],['messages','Messages'],['analytics','Analytics'],['settings','Settings']],
 attendee:[['journey','My Journey'],['map','Live Map'],['navigation','Navigation'],['transport','Transport'],['parking','Parking'],['hotel','Accommodation'],['event','My Event'],['alerts','Alerts'],['profile','Profile']]
};

function toast(title,msg){const el=document.createElement('div');el.className='toast';el.innerHTML=`<b>${title}</b><p>${msg}</p>`;$('#toastHost').appendChild(el);setTimeout(()=>el.remove(),3800)}
function setRole(role){state.role=role; state.page=role==='organizer'?'command':role==='operator'?'overview':'journey'; save(); renderApp(); toast('Role switched',`Now viewing EventFlow as ${role}.`)}
function setPage(p){state.page=p;save();renderContent();$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));if(innerWidth<780) $('.sidebar')?.classList.remove('open')}

function landing(){return `<div class="hero">
  <div class="landing-nav"><div class="brand"><div class="brand-mark">◈</div><div><h1>EVENTFLOW</h1><small>Intelligent orchestration</small></div></div><div class="nav-actions"><button class="btn ghost" onclick="document.querySelector('#features').scrollIntoView()">Explore Platform</button> <button class="btn primary" onclick="openLogin()">Launch EventFlow</button></div></div>
  <div class="hero-inner"><div><div class="eyebrow">City-scale event intelligence</div><h1>One event.<br><em>One intelligence layer.</em></h1><p>Predict crowd pressure, coordinate hospitality and transport capacity, redirect attendees, and keep an entire mega-event moving as one connected operating ecosystem.</p><div class="hero-actions"><button class="btn primary" onclick="openLogin()">Launch Live Demo</button><button class="btn" onclick="demoDirect('organizer')">Enter Command Center</button></div><div style="display:flex;gap:26px;margin-top:35px;color:var(--muted);font-size:12px"><span><b style="color:white">58,420</b><br>simulated attendees</span><span><b style="color:white">12</b><br>connected resource zones</span><span><b style="color:white">87/100</b><br>coordination score</span></div></div>
  <div class="city-visual"><div class="city-panel"><div class="city-grid"></div><div class="building b1"></div><div class="building b2"></div><div class="building b3"></div><div class="building b4"></div><div class="building b5"></div><div class="flowline" style="left:25%;top:38%;width:35%;transform:rotate(16deg)"></div><div class="flowline" style="left:49%;top:49%;width:33%;transform:rotate(-28deg)"></div><div class="flowline" style="left:27%;top:68%;width:28%;transform:rotate(-25deg)"></div>${Array.from({length:26},(_,i)=>`<i class="person" style="left:${15+(i*13)%70}%;top:${20+(i*19)%62}%;animation-delay:-${(i%5)}s"></i>`).join('')}<div class="node warn" style="left:52%;top:34%"><strong>Unity Arena</strong><small>72% load</small></div><div class="node" style="left:18%;top:21%"><strong>Hotel Central</strong><small>71% occupied</small></div><div class="node" style="left:75%;top:18%"><strong>Metro East</strong><small>Normal</small></div><div class="node" style="left:20%;top:76%"><strong>Parking P4</strong><small>33% free</small></div><div class="node" style="left:78%;top:73%"><strong>Shuttle Hub</strong><small>8 active</small></div></div></div></div>
</div>
<section id="features" class="land-section"><div class="eyebrow">Why EventFlow</div><h2>Mega-events are fragmented.<br>EventFlow connects the moving parts.</h2><p>Instead of isolated venue, hotel, parking and transport dashboards, EventFlow creates a shared intelligence layer that predicts pressure and coordinates the response.</p><div class="feature-grid">
${[['01','Event Digital Twin','See venues, gates, transport, parking, hotels and live crowd pressure in one operational map.'],['02','Predictive Crowd Intelligence','Forecast crowd load at 15, 30 and 60-minute horizons before congestion becomes critical.'],['03','Cross-role Orchestration','Organizer decisions become operator assignments and attendee guidance automatically.'],['04','What-If Simulation','Test crowd surges, gate closures, rain, parking saturation and transport failures before acting.'],['05','Intelligent Dispersal','Distribute exit demand across gates, metro stations, parking and shuttle hubs after the event.'],['06','EventFlow Score','Track crowd balance, transport efficiency, accommodation pressure, safety and visitor experience.']].map(x=>`<article class="feature"><div class="num">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section>
<section class="land-section" style="padding-top:10px"><div class="card card-pad" style="text-align:center;padding:55px 20px"><div class="eyebrow">National-level hackathon demo</div><h2 style="margin-top:12px">Orchestrate the entire event ecosystem.</h2><p style="margin:0 auto 26px">Trigger a crowd surge, approve EventFlow recommendations, switch to the operator dashboard, then see attendee routing change—all inside one connected demo.</p><button class="btn primary" onclick="openLogin()">Start EventFlow</button></div></section>`}

function openLogin(){document.body.insertAdjacentHTML('beforeend',`<div class="login-overlay" id="login"><div class="login-box"><div class="eyebrow">Demo access</div><h3>Launch EventFlow</h3><p class="muted">Choose the experience you want to demonstrate.</p><div class="role-cards"><button class="role-card active" data-role="organizer" onclick="pickLoginRole(this)">◈<br><b>Organizer</b><br><small>Command center</small></button><button class="role-card" data-role="operator" onclick="pickLoginRole(this)">◎<br><b>Operator</b><br><small>Capacity & tasks</small></button><button class="role-card" data-role="attendee" onclick="pickLoginRole(this)">➜<br><b>Attendee</b><br><small>Smart journey</small></button></div><input value="demo@eventflow.local" aria-label="Email"><input type="password" value="eventflow" aria-label="Password"><p class="form-note">Demo mode uses simulated data and local browser storage. No external API, paid map service or database is required.</p><button class="btn primary" style="width:100%" onclick="loginNow()">Enter Demo</button><button class="btn ghost" style="width:100%;margin-top:8px" onclick="$('#login').remove()">Cancel</button></div></div>`)}
let loginRole='organizer'; function pickLoginRole(el){loginRole=el.dataset.role;$$('.role-card').forEach(x=>x.classList.remove('active'));el.classList.add('active')} function loginNow(){state.logged=true;state.role=loginRole;state.page=loginRole==='organizer'?'command':loginRole==='operator'?'overview':'journey';save();$('#login')?.remove();renderApp()} function demoDirect(r){state.logged=true;state.role=r;state.page=r==='organizer'?'command':r==='operator'?'overview':'journey';save();renderApp()}

function shell(){return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">◈</div><div><h1>EVENTFLOW</h1><small>${state.role==='organizer'?'Command Center':state.role==='operator'?'Operator Console':'Visitor Assistant'}</small></div></div><div class="nav-label">Navigation</div><div class="nav">${navs[state.role].map(([id,n])=>`<button class="${state.page===id?'active':''}" data-page="${id}" onclick="setPage('${id}')"><span class="ico">${icons[id]||'·'}</span>${n}</button>`).join('')}</div><div class="side-bottom"><div class="role-switch"><button class="${state.role==='organizer'?'active':''}" onclick="setRole('organizer')">Organizer</button><button class="${state.role==='operator'?'active':''}" onclick="setRole('operator')">Operator</button><button class="${state.role==='attendee'?'active':''}" onclick="setRole('attendee')">Attendee</button></div><div class="user-chip"><b>${state.role==='organizer'?'Event Control Room':state.role==='operator'?'MetroLink Operations':'Demo Attendee'}</b><span>National Sports Championship</span></div></div></aside><main class="main"><header class="topbar"><div class="top-left"><button class="topbtn mobile-menu" onclick="$('.sidebar').classList.toggle('open')">☰</button><div class="live-pill"><i class="live-dot"></i> LIVE</div><span class="muted" style="font-size:11px">Last updated <span id="lastUpdated">now</span></span></div><div class="top-right"><input class="search" placeholder="Search gate, venue, hotel, alert... (⌘K)" onclick="openPalette()" readonly><button class="topbtn" onclick="openPalette()">⌘ K</button><button class="topbtn" onclick="showNotifications()">◌ ${state.alerts.length}</button></div></header><div class="content" id="content"></div></main></div>`}

function pageHead(eye,title,desc,actions=''){return `<div class="page-head"><div><div class="eyebrow">${eye}</div><h2>${title}</h2><p>${desc}</p></div><div class="head-actions">${actions}</div></div>`}
function kpi(lab,val,trend='+2.4% vs 5 min'){return `<div class="card kpi card-pad"><div class="lab">${lab}</div><div class="val">${val}</div><div class="trend">${trend}</div></div>`}
function mapMarkup(attendee=false){const surge=state.scenario==='Crowd Surge'||state.gateNorth>80;return `<div class="map"><div class="road ${surge?'critical':'active'}" style="width:49%;left:20%;top:49%;transform:rotate(-8deg)"></div><div class="road active" style="width:33%;left:38%;top:66%;transform:rotate(24deg)"></div><div class="road" style="width:29%;left:14%;top:29%;transform:rotate(31deg)"></div><div class="road" style="width:28%;left:63%;top:28%;transform:rotate(104deg)"></div><div class="crowd ${state.gateNorth>82?'red':state.gateNorth>65?'amber':'green'}" style="width:${70+state.gateNorth}px;height:${70+state.gateNorth}px;left:45%;top:31%;transform:translate(-50%,-50%)"></div><div class="crowd green" style="width:105px;height:105px;left:66%;top:52%;transform:translate(-50%,-50%)"></div><div class="node ${state.gateNorth>82?'crit':'warn'}" style="left:45%;top:31%"><strong>North Gate</strong><small>${state.gateNorth}% density</small></div><div class="node" style="left:67%;top:52%"><strong>East Gate</strong><small>${state.gateEast}% density</small></div><div class="node" style="left:51%;top:69%"><strong>Unity Arena</strong><small>${Math.round(state.inside/420)}% occupied</small></div><div class="node" style="left:17%;top:22%"><strong>${attendee?'Your Location':'Hotel Central'}</strong><small>${attendee?'1.8 km away':'71% occupied'}</small></div><div class="node" style="left:80%;top:22%"><strong>Metro East</strong><small>8 min headway</small></div><div class="node ${state.parking>88?'crit':''}" style="left:18%;top:76%"><strong>Parking P2</strong><small>${state.parking}% occupied</small></div>${Array.from({length:18},(_,i)=>`<i class="person" style="left:${20+(i*17)%55}%;top:${22+(i*23)%55}%;animation-delay:-${i%5}s"></i>`).join('')}<div class="legend"><span><i style="background:var(--green)"></i>Normal</span><span><i style="background:var(--amber)"></i>Moderate</span><span><i style="background:var(--red)"></i>Critical</span></div></div>`}

function commandCenter(){return `${pageHead('Organizer / live operations','Event Command Center','A live city-scale view of crowd pressure, capacity, movement and recommended actions.',`<button class="btn" onclick="setPage('simulation')">Run Simulation</button><button class="btn primary" onclick="triggerScenario('Crowd Surge')">Trigger Crowd Surge</button>`)}<div class="grid kpis">${kpi('Registered Attendees',fmt(state.attendees),'+1,240 today')}${kpi('Currently Inside',fmt(state.inside),'+3.1% inflow')}${kpi('Incoming',fmt(state.incoming),'Peak in 34 min')}${kpi('Active Warnings',state.warnings,state.warnings>4?'Needs attention':'Operational')}${kpi('Transport Load',state.transport+'%',state.transport>80?'Capacity pressure':'Balanced')}${kpi('EventFlow Score',state.score+'/100',state.score>=86?'Strong coordination':'Improving')}</div><div class="grid dashboard-grid"><section class="card map-card"><div class="section-title"><h3>Event Digital Twin</h3><span>${state.scenario} · simulated telemetry</span></div><div class="map-wrap">${mapMarkup(false)}</div></section><div class="stack"><section class="card score-card"><div class="eyebrow">Coordination intelligence</div><div class="score-row"><div class="score-num">${state.score}<span>/100</span></div><span class="status good">● ${state.score>84?'Strong':'Stable'}</span></div><div class="meter"><i style="width:${state.score}%"></i></div><div class="mini-list"><div class="mini-item"><label>Crowd Balance</label><b>${clamp(state.score-3,0,100)}%</b></div><div class="mini-item"><label>Transport Efficiency</label><b>${clamp(100-state.transport/4,0,100).toFixed(0)}%</b></div><div class="mini-item"><label>Visitor Experience</label><b>${clamp(state.score+2,0,100)}%</b></div></div></section><section class="card"><div class="section-title"><h3>Intelligent Alerts</h3><span>${state.alerts.length} active</span></div><div class="alert-list">${alertsHTML(3)}</div></section></div></div><section class="card control-strip"><b style="font-size:11px;padding:9px 5px">Demo Controls</b>${['Normal Traffic','Crowd Surge','Parking Full','Transport Failure','Heavy Rain','Event Finished','Emergency Gate Closure'].map(s=>`<button class="scenario ${state.scenario===s?'active':''}" onclick="triggerScenario('${s}')">${s}</button>`).join('')}</section><div class="grid cards-3">${state.recommendations.map(recCard).join('')}</div><section class="card" style="margin-top:14px"><div class="section-title"><h3>Event Timeline</h3><span>Predicted pressure waves</span></div>${timelineHTML()}</section>`}
function recCard(r){return `<article class="card action-card"><span class="priority">${r.severity}</span><h4>${r.title}</h4><div class="muted" style="font-size:11px">${r.loc}</div><div class="action-meta"><div><small>Current density</small><b>${r.current}%</b></div><div><small>Predicted</small><b>${r.predicted}%</b></div></div><p class="action-text">${r.action}</p><div class="status ${r.approved?'good':'warn'}">${r.approved?'✓ Approved':'Expected impact: '+r.impact}</div><div class="actions"><button class="btn" onclick="simulateRecommendation('${r.id}')">Simulate</button><button class="btn primary" onclick="approveRecommendation('${r.id}')">${r.approved?'Approved':'Approve'}</button></div></article>`}
function alertsHTML(n=99){return state.alerts.slice(0,n).map(a=>`<div class="alert"><div class="a-top"><span class="sev ${a.sev}">${a.sev.toUpperCase()}</span><small>${a.time}</small></div><p>${a.text}</p><small>${a.loc}</small></div>`).join('')||`<div class="muted" style="padding:20px;text-align:center">No active alerts</div>`}
function timelineHTML(){return `<div class="timeline">${[['2:00 PM','Gates Open','Arrival wave'],['3:30 PM','Opening Ceremony','Venue rise'],['5:00 PM','Main Match','Venue peak'],['7:30 PM','Concert','Food-zone peak'],['9:30 PM','Event Finish','Exit surge'],['10:00 PM','Crowd Dispersal','Transport peak']].map((x,i)=>`<div class="t-item ${i===2?'active':''}"><b>${x[0]}</b><span>${x[1]}</span><div class="t-wave">⌁ ${x[2]}</div></div>`).join('')}</div>`}

function triggerScenario(s){state.scenario=s;if(s==='Normal Traffic'){Object.assign(state,{gateNorth:72,gateEast:45,parking:67,transport:63,warnings:3,score:87});toast('Simulation normalized','Event conditions returned to baseline.')}if(s==='Crowd Surge'){Object.assign(state,{gateNorth:92,gateEast:46,transport:84,warnings:7,score:79});state.alerts.unshift({sev:'critical',text:'North Gate projected to exceed safe capacity in 16 minutes.',loc:'North Gate',time:'now'});toast('Crowd surge activated','North Gate pressure is rising. EventFlow generated new cross-role actions.')}if(s==='Parking Full'){state.parking=96;state.warnings=6;state.alerts.unshift({sev:'high',text:'Parking P2 is effectively full. Redirect arriving vehicles to P4.',loc:'Parking P2',time:'now'});toast('Parking pressure simulated','Attendee parking guidance has been updated.')}if(s==='Transport Failure'){state.transport=94;state.score=81;state.alerts.unshift({sev:'critical',text:'Shuttle Route S2 unavailable. Capacity gap detected.',loc:'Shuttle S2',time:'now'});toast('Transport failure simulated','Alternative fleet deployment is recommended.')}if(s==='Heavy Rain'){state.warnings=8;state.score=80;state.alerts.unshift({sev:'high',text:'Heavy rainfall scenario: pedestrian corridors have reduced throughput.',loc:'Event district',time:'now'});toast('Heavy rain scenario','Covered routing and shuttle demand increased.')}if(s==='Event Finished'){state.exiting=12800;state.incoming=320;state.alerts.unshift({sev:'high',text:'Dispersal mode active. Staggered exit guidance enabled.',loc:'Unity Arena',time:'now'});toast('Dispersal mode','Exit demand is being balanced across gates and transport hubs.')}if(s==='Emergency Gate Closure'){state.gateNorth=99;state.warnings=10;state.score=73;state.alerts.unshift({sev:'critical',text:'North Gate closure activated. Safe movement corridor rerouting required.',loc:'North Gate',time:'now'});toast('Emergency demonstration','Affected attendees are being redirected to safe alternative exits.')}save();renderContent()}
function approveRecommendation(id){const r=state.recommendations.find(x=>x.id===id);if(!r)return;r.approved=true;if(id==='r1'){state.gateNorth=71;state.gateEast=63;state.score=84;state.attendeeRoute='East Gate';state.attendeeMessage='North Gate congestion detected. EventFlow has redirected your journey through East Gate. 11 minutes saved.';state.alerts.unshift({sev:'info',text:'700 arriving attendees are being redistributed toward East Gate.',loc:'North → East flow',time:'now'});}if(id==='r2'){let t=state.tasks.find(x=>x.id===1);if(t)t.status='Pending';state.transport=76;state.attendeeMessage='Additional shuttle capacity has been requested. Your route will update automatically.';}if(id==='r3'){state.parking=78;}state.score=clamp(state.score+4,0,100);save();toast('Action approved',r.action);renderContent()}
function simulateRecommendation(id){const r=state.recommendations.find(x=>x.id===id);openModal('Impact Simulation',`<div class="grid cards-3" style="grid-template-columns:1fr 1fr"><div class="card card-pad"><div class="eyebrow">Before</div><h3>${r.predicted}% pressure</h3><p class="muted">Higher congestion risk, longer travel time and resource pressure.</p><div class="meter"><i style="width:${r.predicted}%;background:linear-gradient(90deg,var(--amber),var(--red))"></i></div></div><div class="card card-pad"><div class="eyebrow">After recommended action</div><h3>${Math.max(58,r.current-1)}% pressure</h3><p class="muted">Balanced crowd flow, lower wait time and improved EventFlow coordination score.</p><div class="meter"><i style="width:${Math.max(58,r.current-1)}%"></i></div></div></div><p class="muted" style="margin-top:16px">Simulation uses rule-based demo intelligence and seeded event data.</p>`)}

function organizerGeneric(page){if(page==='map')return `${pageHead('Live spatial intelligence','Event Digital Twin','Click-to-understand operational view of the complete event ecosystem.')}<section class="card map-card"><div class="map-wrap" style="height:650px">${mapMarkup(false)}</div></section>`;if(page==='actions')return `${pageHead('EventFlow Intelligence','AI Action Center','Predictions are converted into operational recommendations that can be approved, simulated or dismissed.')}<div class="grid cards-3">${state.recommendations.map(recCard).join('')}</div>`;if(page==='alerts')return `${pageHead('Operations awareness','Intelligent Alert Center','Critical, high, medium and informational signals across the event ecosystem.')}<section class="card"><div class="alert-list" style="max-height:none">${alertsHTML()}</div></section>`;if(page==='simulation')return simulationPage();if(page==='analytics')return analyticsPage();if(page==='timeline')return `${pageHead('Temporal intelligence','Event Timeline','Operational milestones combined with expected crowd waves and transport pressure.')}<section class="card">${timelineHTML()}</section>`;if(page==='operators')return operatorNetwork();return resourcePage(page)}
function simulationPage(){return `${pageHead('What-if intelligence','Event Scenario Simulator','Test disruptions before taking action and compare the operational state before versus after orchestration.',`<button class="btn primary" onclick="triggerScenario('Normal Traffic')">Reset Baseline</button>`)}<section class="card control-strip">${['Crowd Surge','Parking Full','Transport Failure','Heavy Rain','Event Finished','Emergency Gate Closure'].map(s=>`<button class="scenario ${state.scenario===s?'active':''}" onclick="triggerScenario('${s}')">${s}</button>`).join('')}</section><div class="grid cards-3"><div class="card card-pad"><div class="eyebrow">Crowd level</div><h3>${state.gateNorth}% North Gate</h3><div class="meter"><i style="width:${state.gateNorth}%;background:${state.gateNorth>85?'var(--red)':'linear-gradient(90deg,var(--cyan),var(--violet))'}"></i></div></div><div class="card card-pad"><div class="eyebrow">Travel time impact</div><h3>${state.gateNorth>85?'+14':' +2'} min</h3><p class="muted">Estimated network-wide attendee impact.</p></div><div class="card card-pad"><div class="eyebrow">Safety risk</div><h3>${state.gateNorth>90?'High':state.gateNorth>75?'Moderate':'Low'}</h3><p class="muted">Rule-based simulation result.</p></div></div><section class="card map-card" style="margin-top:14px"><div class="map-wrap">${mapMarkup(false)}</div></section>`}
function analyticsPage(){return `${pageHead('Operational analytics','Event Intelligence Analytics','Animated, simulated performance indicators across crowd, transport, parking and hospitality.')}<div class="grid cards-3"><div class="card"><div class="section-title"><h3>Crowd by time</h3><span>Today</span></div><div class="chart"><canvas id="chart1"></canvas></div></div><div class="card"><div class="section-title"><h3>Transport utilization</h3><span>Live</span></div><div class="chart"><canvas id="chart2"></canvas></div></div><div class="card"><div class="section-title"><h3>Predicted vs actual</h3><span>North Gate</span></div><div class="chart"><canvas id="chart3"></canvas></div></div></div>`}
function resourcePage(page){const map={crowd:['Crowd Intelligence','Predictive zone load','North Gate','East Gate','South Gate','West Gate'],transport:['Transport Coordination','Fleet and route utilization','Metro East','Metro Central','Shuttle S1','Shuttle S3'],hotel:['Accommodation Balance','Hospitality demand and capacity','Hotel Central','Hotel Vista','City Grand','Event Hostel'],parking:['Parking Intelligence','Live zone availability','Parking P1','Parking P2','Parking P3','Parking P4'],settings:['Settings','EventFlow demo configuration','Simulation engine','Language & accessibility','Notification rules','Data reset']};const x=map[page]||map.crowd;return `${pageHead('Connected operations',x[0],x[1])}<section class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Resource</th><th>Current load</th><th>Predicted 30 min</th><th>Capacity status</th><th>Recommendation</th></tr></thead><tbody>${x.slice(2).map((n,i)=>`<tr><td><b>${n}</b></td><td>${[72,45,58,67][i]||54}%</td><td>${[91,63,71,76][i]||68}%</td><td><span class="status ${i===0?'warn':'good'}">${i===0?'Watch':'Available'}</span></td><td>${i===0?'Balance demand proactively':'No action needed'}</td></tr>`).join('')}</tbody></table></div></section>`}
function operatorNetwork(){return `${pageHead('Connected operators','Operator Network','Operational partners connected into one shared orchestration layer.')}<div class="grid cards-3">${[['MetroLink Operations','12 vehicles','94% uptime'],['StayGrid Hospitality','340 rooms free','71% occupied'],['ParkFlow Services','1,230 spaces','67% occupied']].map(x=>`<div class="card card-pad"><div class="eyebrow">Connected partner</div><h3>${x[0]}</h3><p class="muted">${x[1]} · ${x[2]}</p><span class="status good">● Online</span></div>`).join('')}</div>`}

function operatorOverview(){return `${pageHead('Operator console','Capacity & Assignment Overview','Only the operational information relevant to your transport and resource responsibilities.',`<button class="btn primary" onclick="addCapacity()">Add Capacity</button>`)}<div class="grid kpis">${kpi('Fleet Available','18 vehicles','+3 standby')}${kpi('Used Capacity','76%','Moderate pressure')}${kpi('Incoming Demand','+420','Next 30 min')}${kpi('Assigned Tasks',state.tasks.length,state.tasks.some(t=>t.status==='Pending')?'Action required':'On track')}${kpi('Active Routes','6','1 rerouted')}${kpi('Resource Utilization','82%','Efficient')}</div><div class="grid dashboard-grid"><section class="card"><div class="section-title"><h3>Organizer Assignments</h3><span>Cross-role synchronization</span></div><div class="card-pad">${taskHTML()}</div></section><section class="card"><div class="section-title"><h3>Demand Forecast</h3><span>Next 3 hours</span></div><div class="card-pad"><div class="mini-list"><div class="mini-item"><label>Next 30 min</label><b>+420 riders</b></div><div class="mini-item"><label>Next 1 hr</label><b>+1,140 riders</b></div><div class="mini-item"><label>Next 3 hrs</label><b>+2,680 riders</b></div></div><p class="action-text" style="margin-top:18px">Recommendation: stage 3 standby shuttles at Parking P4 before the 9:30 PM exit wave.</p></div></section></div><section class="card" style="margin-top:14px"><div class="section-title"><h3>Fleet Status</h3><span>Live operational state</span></div>${fleetTable()}</section>`}
function taskHTML(){return state.tasks.map(t=>`<div class="alert"><div class="a-top"><span class="sev high">${t.priority.toUpperCase()}</span><span class="status ${t.status==='Completed'?'good':t.status==='In Progress'?'warn':''}">${t.status}</span></div><p><b>${t.title}</b></p><small>${t.pickup} → ${t.destination} · Required capacity ${t.capacity}</small><div class="actions"><button class="btn" onclick="taskStatus(${t.id},'In Progress')">Accept / Start</button><button class="btn primary" onclick="taskStatus(${t.id},'Completed')">Complete</button></div></div>`).join('')}
function taskStatus(id,status){const t=state.tasks.find(x=>x.id===id);if(!t)return;t.status=status;if(status==='In Progress'){state.attendeeMessage='Additional shuttle deployment is in progress. EventFlow is reducing your expected wait time.';state.transport=72;toast('Assignment accepted','Organizer status updated: deployment in progress.')}else{state.attendeeMessage='Additional shuttle capacity is now available near Parking P4 and East Gate.';state.transport=66;state.score=clamp(state.score+3,0,100);toast('Task completed','Organizer and attendee experiences have been updated.')}save();renderContent()}
function addCapacity(){state.transport=clamp(state.transport-6,0,100);toast('Capacity added','2 standby shuttles added to available fleet.');save();renderContent()}
function fleetTable(){return `<div class="table-wrap"><table class="table"><thead><tr><th>Vehicle</th><th>Route</th><th>Occupancy</th><th>Status</th><th>Next trip</th></tr></thead><tbody>${[['SH-104','P4 → Arena','68%','Active','6 min'],['SH-107','Metro East → Arena','82%','Active','4 min'],['SH-112','P3 → East Gate','44%','Standby','12 min'],['BUS-28','Central → Arena','73%','Active','9 min']].map(x=>`<tr>${x.map((v,i)=>`<td>${i===3?`<span class="status ${v==='Active'?'good':'warn'}">${v}</span>`:v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function operatorPage(page){if(page==='overview')return operatorOverview();if(page==='assignments')return `${pageHead('Task coordination','Assignments','Organizer-approved actions appear here automatically.')}<section class="card card-pad">${taskHTML()}</section>`;if(page==='analytics')return analyticsPage();return resourcePage(page==='resources'?'transport':page==='forecast'?'crowd':page==='messages'?'alerts':page)}

function attendeeJourney(){return `${pageHead('Attendee assistant','Your Event Journey','A simple, crowd-aware route from your current location to your seat and back out after the event.',`<select class="btn" onchange="toast('Language changed','Demo language selector: '+this.value)"><option>English</option><option>Hindi</option><option>Marathi</option></select>`)}<div class="grid dashboard-grid"><section class="card journey"><div class="eyebrow">Personal route</div><h3 style="font:650 22px Space Grotesk">Home → Unity Arena</h3>${[['⌂','Home','Depart 4:15 PM','0 min'],['M','Metro Station A','Board Metro East line','22 min'],['S','Event Shuttle S4','Live arrival in 6 min','12 min'],['G',state.attendeeRoute,'Recommended entry','8 min'],['B','Seat Section B','Main Match','6 min']].map(x=>`<div class="journey-step"><div class="jdot">${x[0]}</div><div><b>${x[1]}</b><span>${x[2]}</span></div><span>${x[3]}</span></div>`).join('')}</section><section class="card"><div class="section-title"><h3>Live Guidance</h3><span>Personalized</span></div><div class="card-pad"><div class="status ${state.attendeeRoute==='East Gate'?'warn':'good'}">● Route updated</div><h3 style="line-height:1.4">${state.attendeeMessage}</h3><p class="muted" style="font-size:12px">Guidance is generated from simulated crowd density, gate capacity, shuttle availability and parking pressure.</p><button class="btn primary" onclick="toast('Route activated','Recommended route is now active in your journey.')">Use Recommended Route</button></div></section></div><section class="card" style="margin-top:14px"><div class="section-title"><h3>Crowd-aware route options</h3><span>To Unity Arena</span></div><div class="card-pad route-options"><div class="route-opt"><small>Fastest</small><b>9 min</b><span class="muted">Gate A</span></div><div class="route-opt"><small>Least Crowded</small><b>12 min</b><span class="muted">South Gate</span></div><div class="route-opt"><small>Accessible</small><b>14 min</b><span class="muted">East corridor</span></div><div class="route-opt recommended"><small>EventFlow Recommended</small><b>${state.attendeeRoute==='East Gate'?'8':'10'} min</b><span class="accent">${state.attendeeRoute}</span></div></div></section><section class="card map-card" style="margin-top:14px"><div class="map-wrap">${mapMarkup(true)}</div></section>`}
function attendeePage(page){if(page==='journey')return attendeeJourney();if(page==='map'||page==='navigation')return `${pageHead('Smart navigation','Crowd-Aware Event Map','Simplified live routing without organizer-only operational controls.')}<section class="card map-card"><div class="map-wrap" style="height:650px">${mapMarkup(true)}</div></section>`;if(page==='alerts')return `${pageHead('Personal guidance','Your Alerts','Only the notifications relevant to your journey and event experience.')}<section class="card"><div class="alert-list" style="max-height:none"><div class="alert"><span class="sev info">ROUTE</span><p>${state.attendeeMessage}</p><small>Updated now</small></div>${alertsHTML(2)}</div></section>`;if(page==='hotel')return `${pageHead('Stay intelligence','Accommodation Recommendations','Options balanced by price, availability, travel time and crowd pressure.')}<div class="grid cards-3">${[['Hotel Vista','92% Match','₹3,200/night','2.4 km · Shuttle available'],['City Grand','86% Match','₹2,850/night','3.1 km · Metro nearby'],['Event Hostel','81% Match','₹1,450/night','1.8 km · Shared shuttle']].map(x=>`<div class="card card-pad"><div class="eyebrow">${x[1]}</div><h3>${x[0]}</h3><b>${x[2]}</b><p class="muted">${x[3]}</p><button class="btn">View Journey</button></div>`).join('')}</div>`;return resourcePage(page==='event'?'timeline':page)}

function renderContent(){const c=$('#content');if(!c)return; c.innerHTML=state.role==='organizer'?(state.page==='command'?commandCenter():organizerGeneric(state.page)):state.role==='operator'?operatorPage(state.page):attendeePage(state.page);if(state.page==='analytics')setTimeout(drawCharts,30)}
function renderApp(){const app=$('#app');if(!state.logged){app.innerHTML=landing();return}app.innerHTML=shell();renderContent()}

function openModal(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal" onclick="if(event.target===this)this.remove()"><div class="modal-box"><div class="modal-head"><b>${title}</b><button class="topbtn" onclick="$('#modal').remove()">✕</button></div><div class="modal-body">${body}</div></div></div>`)}
function showNotifications(){openModal('Notification Center',`<div class="alert-list" style="max-height:none">${alertsHTML()}</div>`)}
function openPalette(){openModal('Command Palette',`<div class="grid" style="gap:8px">${[['Open Live Map','map'],['View Critical Alerts','alerts'],['Start Simulation','simulation'],['Go to Transport','transport'],['View AI Actions','actions']].map(x=>`<button class="btn" style="text-align:left" onclick="$('#modal').remove();setPage('${x[1]}')">${x[0]}</button>`).join('')}<button class="btn danger" onclick="resetDemo()">Reset Demo Data</button></div>`)}
function resetDemo(){localStorage.removeItem('eventflow-state');state=JSON.parse(JSON.stringify(baseState));state.logged=true;save();$('#modal')?.remove();renderApp();toast('Demo reset','All EventFlow simulation data restored to baseline.')}

function drawLine(ctx,data,max=100){const w=ctx.canvas.width=ctx.canvas.clientWidth*devicePixelRatio,h=ctx.canvas.height=ctx.canvas.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=ctx.canvas.clientWidth,H=ctx.canvas.clientHeight;ctx.clearRect(0,0,W,H);ctx.strokeStyle='#1f313d';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(0,(H/5)*i);ctx.lineTo(W,(H/5)*i);ctx.stroke()}ctx.strokeStyle='#50e3d4';ctx.lineWidth=2;ctx.beginPath();data.forEach((v,i)=>{let x=10+i*(W-20)/(data.length-1),y=H-15-(v/max)*(H-30);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();data.forEach((v,i)=>{let x=10+i*(W-20)/(data.length-1),y=H-15-(v/max)*(H-30);ctx.fillStyle='#50e3d4';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()})}
function drawBars(ctx,data,max=100){const w=ctx.canvas.width=ctx.canvas.clientWidth*devicePixelRatio,h=ctx.canvas.height=ctx.canvas.clientHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=ctx.canvas.clientWidth,H=ctx.canvas.clientHeight;ctx.clearRect(0,0,W,H);const bw=(W-30)/data.length-8;data.forEach((v,i)=>{ctx.fillStyle=i===data.length-1?'#b39cff':'#50e3d4';ctx.fillRect(15+i*(bw+8),H-15-(v/max)*(H-30),bw,(v/max)*(H-30))})}
function drawCharts(){const a=$('#chart1'),b=$('#chart2'),c=$('#chart3');if(a)drawLine(a.getContext('2d'),[22,31,45,62,81,93,76,58]);if(b)drawBars(b.getContext('2d'),[68,82,44,76,61,88]);if(c)drawLine(c.getContext('2d'),[42,47,55,64,72,state.gateNorth,clamp(state.gateNorth+4,0,100)])}

document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(state.logged)openPalette()}});
setInterval(()=>{if(!state.logged)return;state.inside=clamp(state.inside+Math.round((Math.random()-.38)*90),0,state.attendees);state.incoming=clamp(state.incoming+Math.round((Math.random()-.5)*60),0,20000);if(state.scenario==='Normal Traffic'){state.gateNorth=clamp(state.gateNorth+Math.round((Math.random()-.5)*2),64,77);state.gateEast=clamp(state.gateEast+Math.round((Math.random()-.5)*2),38,54)}save();const lu=$('#lastUpdated');if(lu)lu.textContent='just now';if(state.page==='command'&&state.role==='organizer')renderContent()},7000);
renderApp();
