-- EventFlow hackathon backend schema
-- Run once in Supabase Dashboard -> SQL Editor.
-- Uses authenticated-user policies suitable for a prototype. Tighten role-based policies before production.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  role text not null default 'attendee' check (role in ('organizer','operator','attendee')),
  organization text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id text primary key,
  name text not null,
  venue text not null,
  city text,
  event_date date,
  status text not null default 'live',
  coordination_score integer not null default 87,
  created_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  event_id text not null references public.events(id) on delete cascade,
  severity text not null check (severity in ('critical','high','medium','info')),
  title text not null,
  detail text,
  location text,
  status text not null default 'open',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.operator_tasks (
  id bigint generated by default as identity primary key,
  event_id text not null references public.events(id) on delete cascade,
  title text not null,
  priority text not null default 'medium',
  pickup text,
  destination text,
  required_capacity integer default 0,
  status text not null default 'assigned',
  assigned_operator uuid references auth.users(id) on delete set null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  event_id text not null references public.events(id) on delete cascade,
  owner_id uuid references auth.users(id) on delete set null,
  resource_type text not null,
  name text not null,
  location text,
  total_capacity integer not null default 0,
  available_capacity integer not null default 0,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.event_snapshots (
  id bigint generated by default as identity primary key,
  event_id text not null references public.events(id) on delete cascade,
  venue_occupancy integer,
  hotel_occupancy integer,
  parking_occupancy integer,
  transport_load integer,
  north_gate integer,
  east_gate integer,
  south_gate integer,
  west_gate integer,
  incoming integer,
  inside_count integer,
  coordination_score integer,
  scenario text,
  created_at timestamptz not null default now()
);

create table if not exists public.attendee_journeys (
  id uuid primary key default gen_random_uuid(),
  event_id text not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  recommended_gate text,
  travel_mode text,
  preferred_language text default 'English',
  accessibility_needs text,
  route_state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(event_id, user_id)
);

insert into public.events (id,name,venue,city,event_date,status,coordination_score)
values ('unity-arena-final-2026','National Sports Championship Final','Unity Arena','Mumbai Event District','2026-09-08','live',87)
on conflict (id) do update set name=excluded.name, venue=excluded.venue, city=excluded.city, event_date=excluded.event_date;

-- Automatically mirror basic Auth metadata into profiles.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id,name,role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1)),
    case when new.raw_user_meta_data->>'role' in ('organizer','operator','attendee') then new.raw_user_meta_data->>'role' else 'attendee' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.events enable row level security;
alter table public.alerts enable row level security;
alter table public.operator_tasks enable row level security;
alter table public.resources enable row level security;
alter table public.event_snapshots enable row level security;
alter table public.attendee_journeys enable row level security;

-- Recreate prototype policies safely.
drop policy if exists "profiles readable by authenticated" on public.profiles;
create policy "profiles readable by authenticated" on public.profiles for select to authenticated using (true);
drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);

drop policy if exists "events readable by authenticated" on public.events;
create policy "events readable by authenticated" on public.events for select to authenticated using (true);

drop policy if exists "alerts readable by authenticated" on public.alerts;
create policy "alerts readable by authenticated" on public.alerts for select to authenticated using (true);
drop policy if exists "alerts insert by authenticated" on public.alerts;
create policy "alerts insert by authenticated" on public.alerts for insert to authenticated with check (true);
drop policy if exists "alerts update by authenticated" on public.alerts;
create policy "alerts update by authenticated" on public.alerts for update to authenticated using (true) with check (true);

drop policy if exists "tasks readable by authenticated" on public.operator_tasks;
create policy "tasks readable by authenticated" on public.operator_tasks for select to authenticated using (true);
drop policy if exists "tasks insert by authenticated" on public.operator_tasks;
create policy "tasks insert by authenticated" on public.operator_tasks for insert to authenticated with check (true);
drop policy if exists "tasks update by authenticated" on public.operator_tasks;
create policy "tasks update by authenticated" on public.operator_tasks for update to authenticated using (true) with check (true);

drop policy if exists "resources readable by authenticated" on public.resources;
create policy "resources readable by authenticated" on public.resources for select to authenticated using (true);
drop policy if exists "resources write by authenticated" on public.resources;
create policy "resources write by authenticated" on public.resources for all to authenticated using (true) with check (true);

drop policy if exists "snapshots readable by authenticated" on public.event_snapshots;
create policy "snapshots readable by authenticated" on public.event_snapshots for select to authenticated using (true);
drop policy if exists "snapshots insert by authenticated" on public.event_snapshots;
create policy "snapshots insert by authenticated" on public.event_snapshots for insert to authenticated with check (true);

drop policy if exists "journey own rows" on public.attendee_journeys;
create policy "journey own rows" on public.attendee_journeys for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

-- Optional starter resources.
insert into public.resources (event_id,resource_type,name,location,total_capacity,available_capacity,status,metadata)
select 'unity-arena-final-2026','parking','Parking P4','Southwest approach',1800,1044,'active','{"overflow":true}'::jsonb
where not exists (select 1 from public.resources where event_id='unity-arena-final-2026' and name='Parking P4');

insert into public.resources (event_id,resource_type,name,location,total_capacity,available_capacity,status,metadata)
select 'unity-arena-final-2026','transport','Metro East Shuttle Pool','Metro East',720,202,'active','{"standby_vehicles":2}'::jsonb
where not exists (select 1 from public.resources where event_id='unity-arena-final-2026' and name='Metro East Shuttle Pool');

-- ================================================================
-- LIVE ATTENDEE GPS (privacy-preserving prototype)
-- Each signed-in attendee has one current row. The organizer map does
-- not read raw rows; it calls get_crowd_cells() and receives rounded,
-- short-lived aggregate cells only.
-- ================================================================
create table if not exists public.attendee_locations (
  event_id text not null references public.events(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  accuracy_m integer,
  heading_deg double precision,
  speed_mps double precision,
  last_seen timestamptz not null default now(),
  primary key (event_id, user_id)
);

create index if not exists attendee_locations_event_seen_idx
  on public.attendee_locations (event_id, last_seen desc);

alter table public.attendee_locations enable row level security;

drop policy if exists "attendee location own select" on public.attendee_locations;
create policy "attendee location own select"
  on public.attendee_locations for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "attendee location own insert" on public.attendee_locations;
create policy "attendee location own insert"
  on public.attendee_locations for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "attendee location own update" on public.attendee_locations;
create policy "attendee location own update"
  on public.attendee_locations for update to authenticated
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "attendee location own delete" on public.attendee_locations;
create policy "attendee location own delete"
  on public.attendee_locations for delete to authenticated
  using (auth.uid() = user_id);

create or replace function public.get_crowd_cells(p_event_id text)
returns table(lat double precision, lng double precision, people_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select
    round(al.lat::numeric, 4)::double precision as lat,
    round(al.lng::numeric, 4)::double precision as lng,
    count(*)::bigint as people_count
  from public.attendee_locations al
  where al.event_id = p_event_id
    and al.last_seen > now() - interval '2 minutes'
  group by round(al.lat::numeric, 4), round(al.lng::numeric, 4)
  order by people_count desc
  limit 200;
$$;

revoke all on function public.get_crowd_cells(text) from public;
grant execute on function public.get_crowd_cells(text) to authenticated;

-- Allow the public event map to read only aggregate crowd cells in demo mode.
-- Raw attendee_locations rows remain protected by RLS and are NOT exposed.
grant execute on function public.get_crowd_cells(text) to anon;
