import React, { useEffect, useMemo, useRef, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { CloudRain, MapPinned, RefreshCw, ThermometerSun, Users, Bus, ShieldCheck, Radio, Calendar } from 'lucide-react';
import { OrganizerLayout } from '../../components/organizer/OrganizerLayout';
import { getOrganizerEvents, getStoredEventById } from '../../services/eventStorageService';
import { useAuth } from '../../context/AuthContext';
import { fetchLiveWeather, fetchSocialSignals, getWeatherTwinObservationCount, recordWeatherTwinObservation, resolveEventCoordinates, scenarioFromWeather, simulateWeatherTwin, type LiveWeatherSnapshot, type SocialSignal, type WeatherTwinScenario } from '../../services/weatherTwinService';
import type { AppEvent } from '../../types/event';

const defaultScenario:WeatherTwinScenario={rainMmH:0,temperatureC:30,windKmh:12,stormMinutes:30,floodCm:0};
const riskColor=(v:number)=>v>=75?'#dc2626':v>=52?'#ea580c':v>=28?'#d97706':'#16a34a';
const Slider:React.FC<{label:string;value:number;min:number;max:number;unit:string;onChange:(v:number)=>void}>=({label,value,min,max,unit,onChange})=><label className="block rounded-2xl border border-[#C9D9F7] bg-[#F7FAFF] p-3"><div className="mb-2 flex items-center justify-between text-xs"><span className="font-bold text-[#0B1120]">{label}</span><b className="text-[#2D5FD2]">{value}{unit}</b></div><input className="w-full accent-[#4F7CFF]" type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;

export const OrganizerWeatherTwinPage:React.FC=()=>{
  const {eventId}=useParams<{eventId?:string}>(); const {user}=useAuth(); const navigate=useNavigate();
  const [events,setEvents]=useState<AppEvent[]>([]),[event,setEvent]=useState<AppEvent|null>(null),[weather,setWeather]=useState<LiveWeatherSnapshot|null>(null),[signals,setSignals]=useState<SocialSignal[]>([]),[scenario,setScenario]=useState<WeatherTwinScenario>(defaultScenario),[loading,setLoading]=useState(false);
  const mapRef=useRef<HTMLDivElement|null>(null), mapInstance=useRef<L.Map|null>(null);
  useEffect(()=>{if(!user?.id)return;const list=getOrganizerEvents(user.id);setEvents(list);const target=(eventId&&getStoredEventById(eventId))||list[0];if(target)setEvent(target);},[user?.id,eventId]);
  const load=async(target:AppEvent)=>{setLoading(true);try{const[w,s]=await Promise.all([fetchLiveWeather(target),fetchSocialSignals(target)]);setWeather(w);setSignals(s);setScenario(scenarioFromWeather(w));}catch{const w=await fetchLiveWeather(target);setWeather(w);setSignals([]);setScenario(scenarioFromWeather(w));}finally{setLoading(false);}};
  useEffect(()=>{if(event)load(event);},[event?.id]);
  const observations=event?getWeatherTwinObservationCount(event.id):0; const impact=useMemo(()=>event?simulateWeatherTwin(scenario,event,signals,observations):null,[scenario,event,signals,observations]);
  useEffect(()=>{if(event&&weather&&impact){const t=setTimeout(()=>recordWeatherTwinObservation(event.id,weather,impact),500);return()=>clearTimeout(t);}},[event?.id,weather?.observedAt]);
  useEffect(()=>{if(!event||!impact||!mapRef.current)return;const coords=resolveEventCoordinates(event);mapInstance.current?.remove();const map=L.map(mapRef.current,{zoomControl:true,attributionControl:true}).setView([coords.latitude,coords.longitude],15);mapInstance.current=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);const center:[number,number]=[coords.latitude,coords.longitude];L.circle(center,{radius:280+impact.riskScore*6,color:riskColor(impact.riskScore),fillColor:riskColor(impact.riskScore),fillOpacity:.12,weight:2}).addTo(map);L.circleMarker(center,{radius:9,color:'#0B1120',fillColor:'#4F7CFF',fillOpacity:1,weight:3}).bindPopup(`<b>${event.venue}</b><br/>Risk ${impact.riskScore}/100`).addTo(map);return()=>{map.remove();mapInstance.current=null;};},[event?.id,impact?.riskScore]);
  if(!event||!impact)return <OrganizerLayout pageTitle="Weather Twin"><div className="p-8 text-sm">No event available.</div></OrganizerLayout>;
  const nextRain=weather?.nextRainAt?new Date(weather.nextRainAt).toLocaleString([],{weekday:'short',hour:'2-digit',minute:'2-digit'}):'No rain window';
  return <OrganizerLayout activeEvent={event} onSelectEventId={id=>navigate(`/operations/events/${id}/weather-twin`)} pageTitle="Weather Twin" pageSubtitle="Each event uses its own location and forecast." pageBadge="WEATHER" actions={<button onClick={()=>load(event)} className="inline-flex items-center gap-2 rounded-xl bg-[#4F7CFF] px-3 py-2 text-xs font-bold text-white"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Refresh</button>}>
    <div className="space-y-4 pb-8">
      {events.length>1&&<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{events.map(e=><button key={e.id} onClick={()=>navigate(`/operations/events/${e.id}/weather-twin`)} className={`rounded-2xl border p-3 text-left ${e.id===event.id?'border-[#4F7CFF] bg-[#F7FAFF]':'border-[#C9D9F7] bg-[#F0E9D6]'}`}><div className="flex items-center gap-2"><Calendar className="h-4 w-4 text-[#4F7CFF]"/><b className="text-xs text-[#0B1120]">{e.name}</b></div><span className="mt-1 block text-[10px] text-[#6B6252]">{e.venue} · {e.district||e.state}</span></button>)}</div>}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><CloudRain className="h-5 w-5 text-[#4F7CFF]"/><b className="mt-2 block text-xl text-[#0B1120]">{weather?`${weather.rainMm} mm`:'—'}</b><span className="text-xs text-[#6B6252]">Rain now</span></div><div className="rounded-2xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><ThermometerSun className="h-5 w-5 text-[#4F7CFF]"/><b className="mt-2 block text-xl text-[#0B1120]">{weather?`${weather.temperatureC}°C`:'—'}</b><span className="text-xs text-[#6B6252]">Temperature · {weather?.source||'loading'}</span></div><div className="rounded-2xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><CloudRain className="h-5 w-5 text-[#4F7CFF]"/><b className="mt-2 block text-sm text-[#0B1120]">{nextRain}</b><span className="text-xs text-[#6B6252]">Next rain · {weather?.nextRainProbability??0}%</span></div><div className="rounded-2xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><ShieldCheck className="h-5 w-5" style={{color:riskColor(impact.riskScore)}}/><b className="mt-2 block text-xl text-[#0B1120]">{impact.riskScore}/100</b><span className="text-xs text-[#6B6252]">{impact.riskBand} risk</span></div></div>
      <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><section className="overflow-hidden rounded-3xl border border-[#C9D9F7] bg-white"><div className="flex items-center justify-between px-4 py-3"><div className="flex items-center gap-2"><MapPinned className="h-4 w-4 text-[#4F7CFF]"/><b className="text-sm text-[#0B1120]">{event.name}</b></div><span className="text-xs text-[#6B6252]">{event.venue}</span></div><div ref={mapRef} className="h-[360px] w-full"/></section><section className="rounded-3xl border border-[#C9D9F7] bg-[#0B1120] p-4 text-white"><b className="text-sm">What-if</b><div className="mt-3 grid gap-2"><Slider label="Rain" value={scenario.rainMmH} min={0} max={80} unit=" mm/h" onChange={v=>setScenario({...scenario,rainMmH:v})}/><Slider label="Temperature" value={scenario.temperatureC} min={15} max={50} unit="°C" onChange={v=>setScenario({...scenario,temperatureC:v})}/><Slider label="Wind" value={scenario.windKmh} min={0} max={110} unit=" km/h" onChange={v=>setScenario({...scenario,windKmh:v})}/><Slider label="Flood" value={scenario.floodCm} min={0} max={50} unit=" cm" onChange={v=>setScenario({...scenario,floodCm:v})}/></div></section></div>
      <div className="grid gap-3 md:grid-cols-3"><div className="rounded-2xl border border-[#C9D9F7] bg-[#F7FAFF] p-4"><Bus className="h-4 w-4 text-[#4F7CFF]"/><b className="mt-2 block text-lg text-[#0B1120]">{impact.transportStressPct}%</b><span className="text-xs text-[#6B6252]">Transport stress</span></div><div className="rounded-2xl border border-[#C9D9F7] bg-[#F7FAFF] p-4"><Users className="h-4 w-4 text-[#4F7CFF]"/><b className="mt-2 block text-lg text-[#0B1120]">{impact.gatePressurePct}%</b><span className="text-xs text-[#6B6252]">Gate pressure</span></div><div className="rounded-2xl border border-[#C9D9F7] bg-[#F7FAFF] p-4"><Radio className="h-4 w-4 text-[#4F7CFF]"/><b className="mt-2 block text-lg text-[#0B1120]">{signals.length}</b><span className="text-xs text-[#6B6252]">Public signals</span></div></div>
      <section className="rounded-3xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm text-[#0B1120]">Suggested shifts</b><div className="flex gap-1.5 text-[10px] font-bold"><span className="rounded-full bg-white px-2 py-1 text-emerald-700">P10 {impact.p10Risk}</span><span className="rounded-full bg-white px-2 py-1 text-[#2D5FD2]">P50 {impact.p50Risk}</span><span className="rounded-full bg-white px-2 py-1 text-rose-700">P90 {impact.p90Risk}</span></div></div><div className="mt-3 grid gap-2 md:grid-cols-3">{impact.actions.slice(0,3).map((a,i)=><div key={a} className="rounded-2xl border border-[#C9D9F7] bg-white p-3 text-xs text-[#241E17]"><span className="mr-2 inline-flex h-5 w-5 items-center justify-center rounded-full bg-[#0B1120] text-[10px] font-bold text-white">{i+1}</span>{a}</div>)}</div></section>
    </div>
  </OrganizerLayout>;
};
