import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Activity, AlertTriangle, Car, Bus, DoorOpen, Gauge, RotateCcw, ShieldCheck, SlidersHorizontal, TrendingUp, TrendingDown, Minus, Utensils } from 'lucide-react';
import { OrganizerLayout } from '../../components/organizer/OrganizerLayout';
import { useAuth } from '../../context/AuthContext';
import { getOrganizerEvents, getStoredEventById } from '../../services/eventStorageService';
import { addNotification } from '../../services/notificationService';
import {
  evaluateEventIntelligence, toggleSimulationMode, resetSimulation, applySimulationScenario,
  setResourceSimulationOverride, type EventIntelligenceSnapshot,
} from '../../services/eventIntelligenceService';
import { getStoredActions, initializeDefaultActionsForEvent, updateActionStatus } from '../../services/operationalActionService';
import type { AppEvent } from '../../types/event';
import type { OperationalActionRecord, OperationalActionStatus, ResourceCapacityCalculation } from '../../types/intelligence';

const iconFor=(cat:string)=>cat==='gate'?DoorOpen:cat==='parking'?Car:cat==='transport'?Bus:cat==='food'?Utensils:Gauge;
const statusTone=(v:number)=>v>=90?'border-rose-300 bg-rose-50 text-rose-700':v>=80?'border-amber-300 bg-amber-50 text-amber-700':'border-emerald-200 bg-emerald-50 text-emerald-700';
const TrendIcon=({trend}:{trend:string})=>trend==='INCREASING'?<TrendingUp className="h-3.5 w-3.5 text-rose-600"/>:trend==='DECREASING'?<TrendingDown className="h-3.5 w-3.5 text-emerald-600"/>:<Minus className="h-3.5 w-3.5 text-[#6B6252]"/>;
const Sparkline=({values}:{values:number[]})=>{const pts=(values.length?values:[0]).slice(-8);const min=Math.min(...pts),max=Math.max(...pts);const range=Math.max(1,max-min);const points=pts.map((v,i)=>`${(i/(Math.max(1,pts.length-1)))*100},${30-((v-min)/range)*24}`).join(' ');return <svg viewBox="0 0 100 32" className="h-9 w-full" preserveAspectRatio="none" aria-label="Recent utilization trend"><polyline points={points} fill="none" stroke="#356EE6" strokeWidth="3" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round"/><line x1="0" x2="100" y1="30" y2="30" stroke="#D8E2F1" strokeWidth="1"/></svg>};

export const OrganizerIntelligencePage:React.FC=()=>{
  const {eventId:paramEventId}=useParams<{eventId?:string}>(); const {user}=useAuth();
  const [events,setEvents]=useState<AppEvent[]>([]),[selectedEventId,setSelectedEventId]=useState('');
  const [event,setEvent]=useState<AppEvent|null>(null),[snapshot,setSnapshot]=useState<EventIntelligenceSnapshot|null>(null);
  const [actions,setActions]=useState<OperationalActionRecord[]>([]),[simulating,setSimulating]=useState(false);
  const refresh=(id=selectedEventId)=>{if(!id)return;const e=getStoredEventById(id);if(e)setEvent(e);const next=evaluateEventIntelligence(id);setSnapshot(next);setSimulating(next.simulationState.isSimulationActive);initializeDefaultActionsForEvent(id);setActions(getStoredActions(id));};
  useEffect(()=>{if(!user?.id)return;const list=getOrganizerEvents(user.id);setEvents(list);setSelectedEventId((paramEventId&&list.some(e=>e.id===paramEventId)?paramEventId:list[0]?.id)||'');},[user?.id,paramEventId]);
  useEffect(()=>{refresh(selectedEventId);},[selectedEventId]);
  useEffect(()=>{const fn=()=>refresh(selectedEventId);window.addEventListener('eventflow_intelligence_updated',fn);window.addEventListener('eventflow_action_updated',fn);return()=>{window.removeEventListener('eventflow_intelligence_updated',fn);window.removeEventListener('eventflow_action_updated',fn);};},[selectedEventId]);
  const warnings=snapshot?.earlyWarnings||[],resources=snapshot?.resourceMetrics||[];
  useEffect(()=>{if(!selectedEventId)return;warnings.forEach(w=>addNotification({notificationId:`sim-warning-${w.id}`,userId:'organizer',role:'organizer',eventId:selectedEventId,type:w.severity==='CRITICAL'?'CRITICAL':'WARNING',title:w.resourceName,message:w.reason,createdAt:w.timestamp,read:false,source:w.source,relatedResourceId:w.resourceId,actionLink:paramEventId?`/operations/events/${selectedEventId}/live`:'/operations/live'}));},[selectedEventId,warnings.map(w=>`${w.id}:${w.currentUtilization}`).join('|')]);
  if(!events.length)return <OrganizerLayout pageTitle="Live Command Center"><div className="rounded-3xl border border-[#C9D9F7] bg-[#F0E9D6] p-10 text-center text-sm text-[#6B6252]">Create an event to activate live command.</div></OrganizerLayout>;
  if(!snapshot||!event)return <OrganizerLayout pageTitle="Live Command Center"><div className="p-8 text-sm">Loading operations…</div></OrganizerLayout>;
  const runScenario=(name:'peak_parking'|'gate_surge'|'transit_disruption')=>{applySimulationScenario(selectedEventId,name);refresh(selectedEventId);};
  const setSimulation=(active:boolean)=>{toggleSimulationMode(selectedEventId,active);refresh(selectedEventId);};
  const reset=()=>{resetSimulation(selectedEventId);refresh(selectedEventId);};
  const updateAction=(id:string,status:OperationalActionStatus)=>{updateActionStatus(id,status);setActions(getStoredActions(selectedEventId));};
  const setResourceLoad=(r:ResourceCapacityCalculation,value:number)=>{setResourceSimulationOverride(selectedEventId,r.resourceId,value,r.totalCapacity);refresh(selectedEventId);};
  const utilization=resources.length?Math.round(resources.reduce((s,r)=>s+r.utilizationPercentage,0)/resources.length):0;
  return <OrganizerLayout pageTitle="Live Command Center" pageSubtitle="Capacity, simulations and operational actions." pageBadge="LIVE" activeEvent={event} onSelectEventId={setSelectedEventId}>
    <div className="space-y-5 pb-10">
      <section className="rounded-3xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><SlidersHorizontal className="h-4 w-4 text-[#4F7CFF]"/><div><b className="text-sm text-[#0B1120]">Simulation mode</b><div className="text-[11px] text-[#6B6252]">Adjust resources without changing real operations.</div></div></div><div className="flex flex-wrap gap-2"><button onClick={()=>setSimulation(!simulating)} className={`rounded-xl px-3 py-2 text-xs font-bold ${simulating?'bg-rose-600 text-white':'bg-[#0B1120] text-white'}`}>{simulating?'Stop simulation':'Enable simulation'}</button>{simulating&&<><button onClick={()=>runScenario('peak_parking')} className="rounded-xl border border-[#C9D9F7] bg-white px-3 py-2 text-xs font-bold text-[#0B1120]">Parking surge</button><button onClick={()=>runScenario('gate_surge')} className="rounded-xl border border-[#C9D9F7] bg-white px-3 py-2 text-xs font-bold text-[#0B1120]">Gate surge</button><button onClick={()=>runScenario('transit_disruption')} className="rounded-xl border border-[#C9D9F7] bg-white px-3 py-2 text-xs font-bold text-[#0B1120]">Fleet disruption</button><button onClick={reset} className="rounded-xl border border-[#C9D9F7] bg-white px-3 py-2 text-xs font-bold text-[#0B1120]"><RotateCcw className="mr-1 inline h-3 w-3"/>Reset</button></>}</div></div></section>
      <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-[#C9D9F7] bg-[#F7FAFF] p-4"><Activity className="h-4 w-4 text-[#4F7CFF]"/><b className="mt-2 block text-2xl text-[#0B1120]">{utilization}%</b><span className="text-xs text-[#6B6252]">Average load</span></div><div className="rounded-2xl border border-[#C9D9F7] bg-[#F7FAFF] p-4"><AlertTriangle className="h-4 w-4 text-amber-600"/><b className="mt-2 block text-2xl text-[#0B1120]">{warnings.length}</b><span className="text-xs text-[#6B6252]">Warnings → bell</span></div><div className="rounded-2xl border border-[#C9D9F7] bg-[#F7FAFF] p-4"><ShieldCheck className="h-4 w-4 text-emerald-600"/><b className="mt-2 block text-2xl text-[#0B1120]">{actions.filter(a=>!['VERIFIED','COMPLETED'].includes(a.status)).length}</b><span className="text-xs text-[#6B6252]">Open actions</span></div></div>
      <section className="rounded-3xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><div className="mb-3 flex items-center justify-between"><b className="text-sm text-[#0B1120]">Early warning + action pipeline</b><span className="text-[10px] text-[#6B6252]">Slider impacts update the bell automatically</span></div><div className="grid gap-3 lg:grid-cols-2">{warnings.length?warnings.slice(0,4).map(w=><div key={w.id} className={`rounded-2xl border p-3 ${w.severity==='CRITICAL'?'border-rose-200 bg-rose-50':'border-amber-200 bg-amber-50'}`}><div className="flex items-center justify-between gap-2"><b className="text-xs text-[#0B1120]">{w.resourceName}</b><span className="text-[10px] font-bold text-[#0B1120]">{w.currentUtilization}%</span></div><p className="mt-1 text-xs text-[#5B5143]">{w.reason}</p></div>):<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-800">No early warnings.</div>}{actions.slice(0,4).map(a=><div key={a.actionId} className="rounded-2xl border border-[#C9D9F7] bg-white p-3"><div className="flex items-center justify-between gap-2"><b className="text-xs text-[#0B1120]">{a.title}</b><span className="text-[10px] font-bold text-[#2D5FD2]">{a.status}</span></div><div className="mt-2 flex flex-wrap gap-2">{a.status==='PROPOSED'&&<button onClick={()=>updateAction(a.actionId,'APPROVED')} className="rounded-lg bg-[#356EE6] px-2.5 py-1.5 text-[11px] font-bold text-white">Approve</button>}{a.status==='APPROVED'&&<button onClick={()=>updateAction(a.actionId,'IN_PROGRESS')} className="rounded-lg bg-[#0B1120] px-2.5 py-1.5 text-[11px] font-bold text-white">Start</button>}{a.status==='IN_PROGRESS'&&<button onClick={()=>updateAction(a.actionId,'VERIFIED')} className="rounded-lg bg-emerald-600 px-2.5 py-1.5 text-[11px] font-bold text-white">Verify</button>}</div></div>)}</div></section>
      <section className="rounded-3xl border border-[#C9D9F7] bg-[#F0E9D6] p-4"><div className="mb-4 flex items-end justify-between gap-3"><div><b className="text-sm text-[#0B1120]">Resource capacity</b><div className="text-[11px] text-[#6B6252]">Drag a scale to test load → graph, warnings and available capacity recalculate.</div></div>{simulating&&<span className="rounded-full bg-[#E8F0FF] px-2.5 py-1 text-[10px] font-bold text-[#1F56C5]">SIMULATION ACTIVE</span>}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{resources.map((r:ResourceCapacityCalculation)=>{const Icon=iconFor(r.category);const pct=Math.min(100,r.utilizationPercentage);return <div key={r.resourceId} className="rounded-2xl border border-[#C9D9F7] bg-white p-4"><div className="flex items-start justify-between gap-2"><div className="flex items-center gap-2"><span className="rounded-xl bg-[#F7FAFF] p-2 text-[#2D5FD2]"><Icon className="h-4 w-4"/></span><div><b className="block text-xs text-[#0B1120]">{r.resourceName}</b><span className="text-[10px] uppercase text-[#6B6252]">{r.category} · {r.source}</span></div></div><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${statusTone(r.utilizationPercentage)}`}>{r.utilizationPercentage}%</span></div><div className="mt-3 rounded-xl bg-[#F7FAFF] px-2 py-1"><Sparkline values={r.recentSamples}/><div className="flex items-center justify-between text-[10px]"><span className="flex items-center gap-1 font-bold text-[#0B1120]"><TrendIcon trend={r.trend}/>{r.trend}</span><span className={r.trendDelta>0?'text-rose-600':r.trendDelta<0?'text-emerald-600':'text-[#6B6252]'}>{r.trendDelta>0?'+':''}{r.trendDelta}%</span></div></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="rounded-xl bg-[#F7FAFF] p-2"><b className="block text-sm text-[#0B1120]">{r.totalCapacity}</b><small className="text-[9px] text-[#6B6252]">Capacity</small></div><div className="rounded-xl bg-[#F7FAFF] p-2"><b className="block text-sm text-[#0B1120]">{r.currentUsage}</b><small className="text-[9px] text-[#6B6252]">Load</small></div><div className="rounded-xl bg-[#F7FAFF] p-2"><b className="block text-sm text-emerald-700">{r.availableCapacity}</b><small className="text-[9px] text-[#6B6252]">Available</small></div></div><div className="mt-3"><div className="mb-1 flex justify-between text-[9px] font-bold text-[#6B6252]"><span>0</span><span>IMPACT SCALE</span><span>{r.totalCapacity}</span></div><input aria-label={`Simulate ${r.resourceName} load`} className="w-full accent-[#356EE6]" type="range" min="0" max={Math.max(1,r.totalCapacity)} value={Math.min(r.totalCapacity,r.currentUsage)} onChange={e=>setResourceLoad(r,Number(e.target.value))}/><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-[#E7EEF8]"><span className={`block h-full rounded-full ${pct>=90?'bg-rose-500':pct>=80?'bg-amber-500':'bg-[#356EE6]'}`} style={{width:`${pct}%`}}/></div></div></div>})}</div></section>
    </div>
  </OrganizerLayout>;
};
