import { FACILITIES, facilityLabel } from "../../../shared/facilities";
import { AppEvent } from "../../types/event";
import { useNearbyPlaces } from "../../components/live/useNearbyPlaces";
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { motion, AnimatePresence, useReducedMotion } from 'motion/react';
import { ArrowLeft, ArrowUpRight, Radio, MapPin, Navigation, Users, Shield, ScanLine, LocateFixed, Plus, Copy, Check, X, Activity, Signal, Compass, QrCode, ChevronRight, Map } from 'lucide-react';
import QRCode from 'qrcode';
import { useAuth } from '../../context/AuthContext';
import { getStoredEventById } from '../../services/eventStorageService';
import { VenueMap, VenueZone, LocationPoint } from '../../components/live/VenueMap';
import { PassScanner } from '../../components/live/PassScanner';
import { safeJsonFetch } from '../../services/safeJsonFetch';
import { fallbackLiveVenueApi } from '../../services/liveVenueFallbackService';
import './liveVenue.css';

type Guest = { id: string; secret: string; pass: string };
type Snapshot = { code: string; name: string; center: LocationPoint; radius: number; zones: VenueZone[]; cells: (LocationPoint & { count: number })[]; people?: (LocationPoint & { id:string; label:string; kind:'attendee'|'operator'; simulated?:boolean })[]; active: number; joined: number; inside: number; log: { text: string; at: number }[]; staff: boolean; now: number; demoMode?: boolean; dataSource?: string };
const safeRead = (key: string) => { try { return sessionStorage.getItem(key) || ''; } catch { return ''; } };
function distance(a: LocationPoint, b: LocationPoint) { const rad = Math.PI / 180; const dlat = (b.lat - a.lat) * rad, dlng = (b.lng - a.lng) * rad; const h = Math.sin(dlat/2)**2 + Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlng/2)**2; return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h)); }
const blankZone = { name: '', kind: 'gate', status: 'unknown', note: '', lat: 0, lng: 0, id: '', capacity: undefined as number | undefined, used: undefined as number | undefined, unit: 'spaces' };
export default function LiveVenuePage({ embedded = false, eventOverride, roomOverride, autoStart = false, targetZone = '' }: { embedded?: boolean; eventOverride?: AppEvent; roomOverride?: string; autoStart?: boolean; targetZone?: string } = {}) {
 const { user } = useAuth(); const [search, setSearch] = useSearchParams(); const [localCode,setLocalCode]=useState(''); const code = (roomOverride || localCode || search.get('room') || '').toUpperCase();
 const evt = eventOverride || (search.get('event') ? getStoredEventById(search.get('event')!) : undefined);
 const api = useCallback(async (url: string, body?: unknown, headers: Record<string, string> = {}) => {
  try {
   return await safeJsonFetch<any>('/api/live-venue' + url, { method: body === undefined ? 'GET' : 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: body === undefined ? undefined : JSON.stringify(body) });
  } catch {
   return fallbackLiveVenueApi(url, body, headers, evt);
  }
 }, [evt?.id]);
 useEffect(()=>{let disposed=false;if(evt?.id&&!roomOverride) api('/events/'+encodeURIComponent(evt.id)+'/room').then(d=>{if(!disposed&&d.code)setLocalCode(d.code);}).catch(()=>{});return()=>{disposed=true;};},[evt?.id,roomOverride]);
 const reduced = useReducedMotion();
 const [roomInput, setRoomInput] = useState(code), [snapshot, setSnapshot] = useState<Snapshot | null>(null);
 const [staffKey, setStaffKey] = useState(() => safeRead('ef_staff_' + code)), [keyInput, setKeyInput] = useState('');
 const guestRef = useRef<Guest | null>(null);
 const [guest, setGuest] = useState<Guest | null>(null), [qr, setQr] = useState(''), [showPass, setShowPass] = useState(false);
 const [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [connected, setConnected] = useState(false);
 const [sharing, setSharing] = useState(false), [position, setPosition] = useState<(LocationPoint & { accuracy: number; at: number }) | undefined>();
 const watch = useRef<number | null>(null), lastSend = useRef(0), sharingRef = useRef(false), [focus, setFocus] = useState(0);
 const [placeQuery,setPlaceQuery]=useState('');
 useEffect(()=>{if(targetZone)setSelected(targetZone);},[targetZone]);
 const [selected, setSelected] = useState(''), [filter, setFilter] = useState('all'), [showEditor, setShowEditor] = useState(false), [zone, setZone] = useState(blankZone);
 const [showStaff, setShowStaff] = useState(false), [scanner, setScanner] = useState(false), [scanValue, setScanValue] = useState(''), [direction, setDirection] = useState('entry');
 const [form, setForm] = useState({ name: evt?.name || '', lat: String(evt?.latitude || ''), lng: String(evt?.longitude || ''), radius: '500', setupKey: '' });
 const nearby = useNearbyPlaces(snapshot?.center.lat,snapshot?.center.lng);
 const allZones = [...(snapshot ? [{id:'event-venue',name:snapshot.name,kind:'venue',lat:snapshot.center.lat,lng:snapshot.center.lng,status:'unknown',note:'Event venue location. Follow your ticket for the assigned gate.',updatedAt:0}] : []), ...(snapshot?.zones || []), ...nearby.places];
 const autoStarted = useRef(false);
 useEffect(()=>{if(autoStart && snapshot && !autoStarted.current){autoStarted.current=true;startSharing();}},[autoStart,Boolean(snapshot)]);
 const [now, setNow] = useState(Date.now()), [lastSync, setLastSync] = useState(0);
 useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 5000); return () => clearInterval(timer); }, []);
 useEffect(() => { setSnapshot(null); setStaffKey(safeRead('ef_staff_' + code)); setSelected(''); setError(''); setPosition(undefined); setSharing(false); setShowPass(false); try { setGuest(JSON.parse(safeRead('ef_guest_' + code) || 'null')); } catch { setGuest(null); } }, [code]);
 const refresh = useCallback(async () => { if (!code) return; try { const data = await api('/rooms/' + code, undefined, { 'X-Venue-Token': staffKey }); setSnapshot(data); if (staffKey && !data.staff && !data.demoMode) setError('Staff key was not accepted. Ask the room creator for the correct key.'); setConnected(true); setLastSync(Date.now()); setError(''); } catch { setConnected(false); setError('Live data is temporarily unavailable. The venue map remains usable in simulation mode.'); } }, [code, staffKey, api]);
 useEffect(() => { let cancelled = false; let timer: ReturnType<typeof setTimeout>; const poll = async () => { if (cancelled) return; await refresh(); if (!cancelled) timer = setTimeout(poll, 4000); }; poll(); return () => { cancelled = true; clearTimeout(timer); }; }, [refresh]);
 guestRef.current = guest;
 useEffect(() => { if (guest) QRCode.toDataURL(guest.pass, { width: 260, margin: 2, color: { dark: '#102a36', light: '#ffffff' } }).then(setQr); else setQr(''); }, [guest]);
 useEffect(() => () => {
  sharingRef.current = false; if (watch.current !== null) navigator.geolocation.clearWatch(watch.current);
  const guest = guestRef.current;
  if (guest) fetch('/api/live-venue/rooms/' + code + '/position', { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Guest-Token': guest.secret }, body: JSON.stringify({ id: guest.id, stop: true }), keepalive: true }).catch(() => {});
 }, [code]);
 async function action(fn: () => Promise<void>) { setError(''); setNotice(''); setBusy(true); try { await fn(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 async function ensureGuest() { if (guest) return guest; const g = await api('/rooms/' + code + '/join', {}); sessionStorage.setItem('ef_guest_' + code, JSON.stringify(g)); setGuest(g); return g as Guest; }
 async function startSharing() {
  await action(async () => {
   if (!window.isSecureContext || !navigator.geolocation) throw new Error('Location requires HTTPS or localhost. Your pass and venue updates still work.');
   const g = await ensureGuest(); sharingRef.current = true; setSharing(true); lastSend.current = 0;
   watch.current = navigator.geolocation.watchPosition(p => {
    if (!sharingRef.current) return;
    const loc = { lat: p.coords.latitude, lng: p.coords.longitude, accuracy: p.coords.accuracy, at: Date.now() }; setPosition(loc);
    if (Date.now() - lastSend.current < 8000) return; lastSend.current = Date.now();
    api('/rooms/' + code + '/position', { id: g.id, position: loc }, { 'X-Guest-Token': g.secret }).then(refresh).catch(e => setError(e.message));
   }, e => { setError(e.code === 1 ? 'Location permission denied. You can still view the map and use your attendance pass.' : 'Location unavailable. Try outdoors or use the venue map.'); stopSharing(g); }, { enableHighAccuracy: true, maximumAge: 5000, timeout: 20000 });
  });
 }
 async function stopSharing(g = guest) {
  sharingRef.current = false; if (watch.current !== null) navigator.geolocation.clearWatch(watch.current); watch.current = null; setSharing(false); setPosition(undefined);
  if (g) try { await api('/rooms/' + code + '/position', { id: g.id, stop: true }, { 'X-Guest-Token': g.secret }); await refresh(); } catch { setError('Location stopped on this phone. Server observations expire within two minutes.'); }
 }
 async function copy(value: string) { try { await navigator.clipboard.writeText(value); setNotice('Copied to clipboard.'); } catch { setError('Clipboard unavailable. Select and copy the displayed text.'); } }
 async function createRoom() { await action(async () => { const r = await api('/rooms', { name: form.name, center: { lat: Number(form.lat), lng: Number(form.lng) }, radius: Number(form.radius), eventId: evt?.id, setupKey: form.setupKey }); sessionStorage.setItem('ef_staff_' + r.code, r.staffToken); if(embedded)setLocalCode(r.code);else setSearch({ room: r.code }); setShowStaff(true); }); }
 async function scan(pass: string) { setScanner(false); await action(async () => { await api('/rooms/' + code + '/scan', { pass: pass.trim(), direction }, { 'X-Venue-Token': staffKey }); setNotice(direction === 'entry' ? 'Entry recorded. Attendance count updated.' : 'Exit recorded. Attendance count updated.'); setScanValue(''); await refresh(); }); }
 const currentPosition = position && now - position.at < 120000 ? position : undefined;
 const activeZone = allZones.find(z => z.id === selected);
 const staleZone = activeZone && activeZone.source !== 'osm' && now - activeZone.updatedAt > 900000;
 const listedZones = allZones.filter(z => (filter === 'all' || z.kind === filter) && z.name.toLowerCase().includes(placeQuery.toLowerCase()));
 const proximity = currentPosition && snapshot ? distance(currentPosition, snapshot.center) : undefined;
 const nearText = proximity === undefined ? 'Location not shared' : currentPosition!.accuracy > 100 ? 'Location accuracy is low' : proximity + currentPosition!.accuracy < snapshot!.radius ? 'Within venue proximity area' : proximity - currentPosition!.accuracy > snapshot!.radius ? 'Outside venue proximity area' : 'Near boundary · location uncertain';
 const directions = activeZone && (activeZone.source === 'osm' || (!staleZone && !['closed','crowded','unknown'].includes(activeZone.status))) ? `https://www.google.com/maps/dir/?api=1&destination=${activeZone.lat},${activeZone.lng}&travelmode=walking` : undefined;
 return <div className={"ef-live " + (embedded ? "ef-embedded" : "")}>
  {!embedded && <header className="ef-topbar"><Link to={user?.role === 'organizer' ? '/operations' : user?.role === 'operator' ? '/operators' : '/my-event'} className="ef-back"><ArrowLeft size={17} /><span>Back to EventFlow</span></Link><Link to="/" className="ef-brand"><span className="ef-brand-icon"><Activity size={21}/></span>eventflow<span className="ef-brand-dot">.</span></Link><span className="ef-top-label"><Shield size={14}/> YOUR EVENT, CONNECTED</span></header>}
  <main className="ef-main">
   {!embedded && <motion.section initial={reduced ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="ef-intro">
    <div><div className="ef-eyebrow"><span className="ef-pulse"/> LIVE VENUE COMPANION</div><h1>Your place.<br/><span>Your next move.</span></h1><p>{snapshot ? snapshot.name : 'A clearer way through the crowd. Connect to your event and find your way, together.'}</p></div>
    <div className="ef-orbit" aria-hidden="true"><div className="ef-orbit-ring"/><div className="ef-orbit-ring inner"/><div className="ef-orbit-center"><Navigation size={31}/></div><span className="ef-orbit-point one"/><span className="ef-orbit-point two"/><span className="ef-orbit-caption">CONNECTED IN REAL TIME</span></div>
   </motion.section>}
   <AnimatePresence>{(error || notice) && <motion.div role={error ? 'alert' : 'status'} initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className={'ef-message ' + (error ? 'error' : '')}><span>{error || notice}</span><button aria-label="Dismiss message" onClick={() => { setError(''); setNotice(''); }}><X size={16}/></button></motion.div>}</AnimatePresence>
   {!embedded && <Link className="ef-launch" to={`/venue-3d?room=${encodeURIComponent(code)}&name=${encodeURIComponent(snapshot?.name || evt?.name || 'Event Venue')}`}><Map size={24}/><span><strong>Open indoor floor map</strong><small>2D indoor route, facilities, live volunteers and assistance</small></span><ChevronRight size={19}/></Link>}
   {!snapshot && <section className="ef-entry-grid">
    <div className="ef-panel ef-join"><div className="ef-icon-box"><Radio size={24}/></div><h2>Step into your event.</h2><p>Enter the room code shared by your organizer. No location access until you choose to share.</p><form onSubmit={e => { e.preventDefault(); if(embedded)setLocalCode(roomInput.trim().toUpperCase());else setSearch({ room: roomInput.trim().toUpperCase() }); }}><label>LIVE ROOM CODE<input required maxLength={8} placeholder="E.g. A1B2C3D4" value={roomInput} onChange={e => setRoomInput(e.target.value.toUpperCase())}/></label><button className="ef-btn" type="submit">Connect to event <ArrowUpRight size={18}/></button></form><span className="ef-small">{code ? 'Connecting to your shared venue…' : 'Your original bookings and tickets stay in My Events.'}</span></div>
    <div className="ef-panel"><div className="ef-eyebrow muted">FOR EVENT TEAMS</div><h2>Open a live venue.</h2><p>Use your actual venue coordinates. Map gates and facilities where they really are.</p><form onSubmit={e => { e.preventDefault(); createRoom(); }} className="ef-form"><label>EVENT NAME<input required maxLength={140} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your event name"/></label><div className="ef-two"><label>LATITUDE<input required type="number" step="any" min="-85" max="85" value={form.lat} onChange={e => setForm({ ...form, lat: e.target.value })}/></label><label>LONGITUDE<input required type="number" step="any" min="-180" max="180" value={form.lng} onChange={e => setForm({ ...form, lng: e.target.value })}/></label></div><label>PROXIMITY RADIUS · METRES<input type="number" min="50" max="5000" required value={form.radius} onChange={e => setForm({ ...form, radius: e.target.value })}/></label><label>HOST SETUP PASSWORD<input type="password" autoComplete="off" value={form.setupKey} onChange={e => setForm({ ...form, setupKey: e.target.value })} placeholder="Required on a production host"/></label><button disabled={busy} className="ef-btn secondary">{busy ? 'Opening…' : 'Create live room'}<Plus size={17}/></button></form></div>
   </section>}
   {snapshot && <>
    <div className="ef-room-strip"><div className="ef-connection"><span className={'ef-dot ' + (connected ? 'online' : '')}/>{snapshot?.demoMode ? 'DEMO SIMULATION' : connected ? 'LIVE DATA' : 'Connection interrupted'}<span>Updated {Math.max(0, Math.floor((now-lastSync)/1000))}s ago</span></div><button className="ef-code" onClick={() => copy(window.location.origin + '/live-venue?room=' + code)}>ROOM {code}<Copy size={14}/></button></div>
    <div className="ef-stats">{[{ label: 'Recorded inside', value: snapshot.inside, icon: Users, detail: 'Staff-scanned entries minus exits' }, { label: 'Sharing now', value: snapshot.active, icon: Signal, detail: 'Near venue · recent accuracy ≤100m' }, { label: 'Mapped places', value: snapshot.zones.length, icon: MapPin, detail: 'Placed by your event team' }].map((s,i) => <motion.div className="ef-stat" key={s.label} initial={reduced ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i*.07 }}><div className="ef-stat-top"><span>{s.label}</span><s.icon size={18}/></div><strong key={s.value}>{s.value.toLocaleString()}</strong><small>{s.detail}</small></motion.div>)}</div>
    <section className="ef-workspace">
     <div className="ef-map-card"><div className="ef-map-heading"><div><span className="ef-eyebrow muted">THE VENUE, AT A GLANCE</span><h2>Find your flow.</h2></div><button className="ef-round" aria-label="Recenter map" onClick={() => setFocus(v=>v+1)}><LocateFixed size={20}/></button></div>
      <VenueMap center={snapshot.center} radius={snapshot.radius} zones={listedZones} cells={snapshot.cells} people={snapshot.people || []} position={currentPosition} selected={selected} onSelect={setSelected} focus={focus} onPick={snapshot.staff && showEditor ? p => setZone(z=>({ ...z,...p })) : undefined}/>
      <div className="ef-legend"><span><i className="green"/>Normal</span><span><i className="amber"/>Busy</span><span><i className="red"/>Crowded</span><span><i className="grey"/>Closed / unknown</span><span><i className="purple"/>Sharing devices</span></div><p className="ef-map-note">Crowd colours are staff observations, not Google traffic. Purple areas show consenting devices, not total attendance. Observations turn unknown after 15 minutes.</p>
     </div>
     <aside className="ef-side"><div className="ef-presence"><div className="ef-presence-top"><span className="ef-icon-box"><Navigation size={22}/></span><span className="ef-chip">YOU ARE IN CONTROL</span></div><h2>Are you at<br/>the event?</h2><p>Share your location to see where you are and contribute to the live venue view.</p><button disabled={busy} className={'ef-btn ' + (sharing ? 'stop' : '')} onClick={() => sharing ? stopSharing() : startSharing()}>{sharing ? 'Stop sharing location' : 'I’m here · Start guidance'}{sharing ? <X size={17}/> : <Navigation size={17}/>}</button><div className="ef-location-status"><span className={'ef-dot ' + (currentPosition ? 'online' : '')}/>{nearText}</div>{currentPosition && <small>Accuracy ±{Math.round(currentPosition.accuracy)}m · {Math.max(0,Math.floor((now-currentPosition.at)/1000))}s ago</small>}<p className="ef-small">Keep this page visible for updates. Sharing location does not verify ticket entry.</p></div>
      <button className="ef-pass-button" disabled={busy} onClick={() => action(async () => { await ensureGuest(); setShowPass(true); })}><QrCode size={24}/><span><strong>My attendance pass</strong><small>For the Live Venue entry desk</small></span><ChevronRight size={19}/></button>
      <div className="ef-insight"><Activity size={18}/><div><strong>Honest by design.</strong><p>{snapshot.active === 0 ? 'No recent locations yet. The map will update when attendees choose to share.' : `${snapshot.active} device${snapshot.active === 1 ? ' is' : 's are'} sharing. This sample cannot establish the total crowd or a safe route.`}</p></div></div>
     </aside>
    </section>
    <section className="ef-bottom-grid"><div className="ef-panel"><div className="ef-section-head"><div><div className="ef-eyebrow muted">YOUR NEXT STOP</div><h2>Places that matter.</h2></div><Compass size={25}/></div><p className="ef-small">{nearby.loading ? "Finding nearby parking, hotels and restaurants…" : nearby.error || "Nearby directory + event-team locations. Directory availability is not live."}</p>{nearby.error && <button className="ef-btn secondary" onClick={nearby.retry}>Retry nearby search</button>}<input aria-label="Search all venue places" placeholder="Search gates, hotels, stalls, security…" value={placeQuery} onChange={e=>setPlaceQuery(e.target.value)}/><div className="ef-filters">{['all',...FACILITIES.map(f=>f[0])].map(f=><button className={filter===f ? 'active' : ''} key={f} onClick={()=>setFilter(f)}>{f==='all'?'All places':facilityLabel(f)}</button>)}</div>
      {listedZones.length === 0 ? <div className="ef-empty"><MapPin size={27}/><strong>No {filter==='all'?'places':filter+' points'} mapped yet</strong><p>The event team can add exact locations using Staff controls. We won’t invent gates or paths.</p></div> : <div className="ef-place-list">{listedZones.map(z=><button key={z.id} className={'ef-place '+(selected===z.id?'active':'')} onClick={()=>setSelected(z.id)}><span className={'ef-place-dot '+(now-z.updatedAt>900000?'unknown':z.status)}/><span><strong>{z.name}</strong><small>{facilityLabel(z.kind)} · {z.source==='osm'?'Directory listing':now-z.updatedAt>900000?'Needs update':z.status}</small></span><ChevronRight size={16}/></button>)}</div>}
      {activeZone && <div className="ef-destination"><strong>{activeZone.name}</strong>{activeZone.capacity !== undefined && !staleZone && <p><b>{Math.max(0,activeZone.capacity-(activeZone.used||0))} / {activeZone.capacity} {activeZone.unit||'spaces'} available</b> · staff reported</p>}<p>{activeZone.note || (activeZone.source==='osm' ? 'Directory location only. Opening hours, room availability and occupancy are not live.' : 'No additional instructions from staff.')}</p><small>{activeZone.source==='osm'?'Source: OpenStreetMap directory':'Updated '+new Date(activeZone.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small>{directions ? <a className="ef-btn secondary" href={directions} target="_blank" rel="noreferrer">Open walking directions<ArrowUpRight size={16}/></a> : <p className="ef-route-hold">{staleZone || activeZone.status==='unknown' ? 'Ask staff for a current access update before travelling here.' : 'Guidance paused for this location. Ask event staff for an approved alternative.'}</p>}<p className="ef-small">External directions do not include EventFlow crowd observations. Follow venue signage and staff for internal paths.</p></div>}
     </div><div className="ef-panel"><div className="ef-section-head"><div><div className="ef-eyebrow muted">FROM YOUR EVENT TEAM</div><h2>What’s changing.</h2></div><Radio size={22}/></div><div className="ef-timeline">{snapshot.log.slice(0,6).map((l,i)=><motion.div key={l.at+':'+i} initial={reduced ? false : {opacity:0,x:8}} animate={{opacity:1,x:0}} className="ef-timeline-item"><span/><div><small>{new Date(l.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small><p>{l.text}</p></div></motion.div>)}</div><div className="ef-team-note"><Shield size={18}/><span>Only paired staff can publish venue observations and record attendance.</span></div></div></section>
    {(!embedded || user?.role !== "attendee") && <section className="ef-staff"><button className="ef-staff-toggle" onClick={()=>setShowStaff(v=>!v)}><Shield size={18}/><strong>Staff controls</strong><span>{snapshot.staff?'Paired to this venue':'Pair with a staff key'}</span><Plus size={18}/></button>{showStaff && <div className="ef-staff-body">{!snapshot.staff ? <form onSubmit={e=>{e.preventDefault();sessionStorage.setItem('ef_staff_'+code,keyInput);setStaffKey(keyInput);}} className="ef-inline-form"><label>STAFF KEY<input type="password" required value={keyInput} onChange={e=>setKeyInput(e.target.value)} placeholder="Ask the room creator"/></label><button className="ef-btn">Pair this device</button></form> : <>
     <div className="ef-staff-actions"><button className="ef-btn secondary" onClick={()=>{setZone({...blankZone,...snapshot.center});setShowEditor(v=>!v);}}><Plus size={16}/>Map a place</button><button className="ef-btn secondary" onClick={()=>copy(staffKey)}><Copy size={16}/>Copy private staff key</button><span className="ef-small">Share the key only with your event team. It grants edit and scan access.</span></div>
     {showEditor && <form className="ef-editor" onSubmit={e=>{e.preventDefault();action(async()=>{await api('/rooms/'+code+'/zones',zone,{'X-Venue-Token':staffKey});setShowEditor(false);setNotice('Place published to every connected device.');await refresh();});}}><p>Click the map to choose the exact position, or enter coordinates below.</p><div className="ef-two"><label>PLACE NAME<input required maxLength={80} value={zone.name} onChange={e=>setZone({...zone,name:e.target.value})}/></label><label>TYPE<select value={zone.kind} onChange={e=>setZone({...zone,kind:e.target.value})}>{FACILITIES.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label><label>LATITUDE<input type="number" step="any" required min="-85" max="85" value={zone.lat} onChange={e=>setZone({...zone,lat:Number(e.target.value)})}/></label><label>LONGITUDE<input type="number" step="any" required min="-180" max="180" value={zone.lng} onChange={e=>setZone({...zone,lng:Number(e.target.value)})}/></label><label>CURRENT OBSERVATION<select value={zone.status} onChange={e=>setZone({...zone,status:e.target.value})}>{['unknown','normal','busy','crowded','closed'].map(v=><option key={v}>{v}</option>)}</select></label><label>INSTRUCTIONS<input maxLength={240} value={zone.note} onChange={e=>setZone({...zone,note:e.target.value})} placeholder="Advice for attendees"/></label><label>CAPACITY (OPTIONAL)<input type="number" min="0" value={zone.capacity ?? ""} onChange={e=>setZone({...zone,capacity:e.target.value===""?undefined:Number(e.target.value),used:e.target.value===""?undefined:zone.used})}/></label><label>CURRENTLY USED<input type="number" min="0" max={zone.capacity} required={zone.capacity!==undefined} disabled={zone.capacity===undefined} value={zone.used ?? ""} onChange={e=>setZone({...zone,used:e.target.value===""?undefined:Number(e.target.value)})}/></label><label>UNIT<select value={zone.unit} onChange={e=>setZone({...zone,unit:e.target.value})}>{["spaces","rooms","people","seats"].map(v=><option key={v}>{v}</option>)}</select></label></div><button disabled={busy} className="ef-btn">Publish observation<Check size={16}/></button></form>}
     <div className="ef-staff-zones">{snapshot.zones.map(z=><button className="ef-btn secondary" key={z.id} onClick={()=>{setZone({...blankZone,...z});setShowEditor(true);setSelected(z.id);}}>{z.name}<span>Update</span></button>)}</div>
     <div className="ef-scan-desk"><h3>Attendance desk</h3><p>Scan the separate Live Venue attendance pass after checking the attendee’s original admission ticket. This records presence; it does not validate payment or ticket authenticity.</p><div className="ef-inline-form"><label>DIRECTION<select value={direction} onChange={e=>setDirection(e.target.value)}><option value="entry">Entry</option><option value="exit">Exit</option></select></label><button className="ef-btn secondary" onClick={()=>setScanner(true)}><ScanLine size={17}/>Open scanner</button></div>{scanner && <PassScanner onScan={scan} onClose={()=>setScanner(false)}/>}<form className="ef-inline-form" onSubmit={e=>{e.preventDefault();scan(scanValue);}}><label>OR PASTE ATTENDANCE PASS<input required value={scanValue} onChange={e=>setScanValue(e.target.value)} placeholder="EFV:…"/></label><button disabled={busy} className="ef-btn">Record {direction}</button></form></div>
    </>}</div>}</section>}
   </>}
   <footer className="ef-footer"><span>EVENTFLOW / LIVE VENUE</span><span>Built around people. Grounded in real updates.</span></footer>
  </main>
  <AnimatePresence>{showPass && <motion.div className="ef-modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setShowPass(false)}><motion.div role="dialog" aria-modal="true" aria-label="Attendance pass" className="ef-modal" initial={reduced?false:{scale:.95,y:20}} animate={{scale:1,y:0}} onClick={e=>e.stopPropagation()}><button className="ef-modal-close" aria-label="Close pass" onClick={()=>setShowPass(false)}><X size={20}/></button><div className="ef-eyebrow muted">LIVE VENUE ATTENDANCE</div><h2>Your presence, connected.</h2><p>{snapshot?.name}</p>{qr && <img src={qr} width={260} height={260} alt="Live Venue attendance QR"/>}<p className="ef-small">Show this to paired staff after your admission ticket is checked. Location sharing is optional.</p><button className="ef-btn secondary" onClick={()=>guest&&copy(guest.pass)}><Copy size={16}/>Copy pass for manual entry</button><button className="ef-btn" onClick={()=>setShowPass(false)}>Done</button></motion.div></motion.div>}</AnimatePresence>
 </div>;
}
