import assert from 'node:assert/strict';
import chromiumBinary from '/tmp/ef-browser/node_modules/@sparticuz/chromium/build/index.js';
import { chromium } from '/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
const base='http://127.0.0.1:3000';
async function api(route, body, token) { const r=await fetch(base+'/api/live-venue'+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{'X-Venue-Token':token}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json()}; }
const room=(await api('/rooms',{name:'EventFlow · Mumbai Live Test',center:{lat:18.9389,lng:72.8258},radius:500})).data;
assert.ok(room.code); const root='/rooms/'+room.code;
assert.equal((await api(root+'/zones',{name:'Gate A',lat:18.939,lng:72.826,kind:'gate',status:'normal'})).status,403);
assert.equal((await api(root+'/zones',{name:'East Gate',lat:18.939,lng:72.826,kind:'gate',status:'normal',note:'Entry open. Follow your ticket gate assignment.'},room.staffToken)).status,200);
await api(root+'/zones',{name:'North Concourse',lat:18.940,lng:72.825,kind:'zone',status:'crowded',note:'Crowd building. Please ask a steward for guidance.'},room.staffToken);
await api(root+'/zones',{name:'Water Point',lat:18.938,lng:72.824,kind:'water',status:'normal',note:'Water refill available.'},room.staffToken);
const browser=await chromium.launch({headless:true,proxy:process.env.HTTPS_PROXY?{server:process.env.HTTPS_PROXY,bypass:'127.0.0.1,localhost'}:undefined,executablePath:'/tmp/ef-chromium',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote'],env:{...process.env,LD_LIBRARY_PATH:'/tmp/ef-chrome-libs',FONTCONFIG_PATH:'/etc/fonts'}});
const attendee=await browser.newContext({viewport:{width:1440,height:1100},permissions:['geolocation'],geolocation:{latitude:18.939,longitude:72.825,accuracy:12}});
const page=await attendee.newPage(); const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/live-venue?room='+room.code);await page.getByRole('heading',{name:'Find your flow.'}).waitFor();
await page.getByRole('button',{name:'I’m here · Start guidance'}).click();
await page.getByText('Within venue proximity area',{exact:true}).waitFor({timeout:15000});
await page.waitForTimeout(1200);
let state=(await api(root)).data; assert.equal(state.active,1); assert.equal(state.inside,0); assert.equal(state.guests,undefined); assert.equal(state.staffHash,undefined);
await page.getByRole('button',{name:/My attendance pass/}).click();await page.getByRole('dialog').waitFor();
const guest=await page.evaluate(code=>JSON.parse(sessionStorage.getItem('ef_guest_'+code)),room.code);
assert.ok(guest.pass.startsWith('EFV:'));
assert.equal((await api(root+'/scan',{pass:guest.pass,direction:'entry'},room.staffToken)).status,200);
assert.equal((await api(root+'/scan',{pass:guest.pass,direction:'entry'},room.staffToken)).status,409);
assert.equal((await api(root)).data.inside,1);
assert.equal((await api(root+'/scan',{pass:guest.pass,direction:'exit'},room.staffToken)).status,200);
assert.equal((await api(root)).data.inside,0);
await page.getByRole('button',{name:'Done',exact:true}).click();
await page.getByRole('button',{name:'Stop sharing location'}).click();assert.equal((await api(root)).data.active,0);
await page.getByRole('button',{name:'East Gate gate · normal'}).click();await page.getByRole('link',{name:'Open walking directions'}).waitFor();
const zone=(await api(root)).data.zones.find(z=>z.name==='East Gate');await api(root+'/zones',{...zone,status:'closed',note:'Temporarily closed by staff.'},room.staffToken);
await page.getByText('Guidance paused for this location.',{exact:false}).waitFor({timeout:10000});assert.equal(await page.getByRole('link',{name:'Open walking directions'}).count(),0);
console.log('MAP_TILES',await page.locator('.leaflet-tile-loaded').count());console.log('PADDING',await page.locator('.ef-presence').evaluate(el=>getComputedStyle(el).padding));await page.screenshot({path:'checks/live-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'checks/live-mobile.png',fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Mobile overflow');
const staff=await browser.newContext({viewport:{width:1440,height:1000}});const op=await staff.newPage();op.on('pageerror',e=>errors.push(e.message));await op.goto(base+'/live-venue?room='+room.code);await op.getByRole('button',{name:/Staff controls/}).click();await op.getByLabel('STAFF KEY',{exact:true}).fill(room.staffToken);await op.getByRole('button',{name:'Pair this device'}).click();await op.getByRole('button',{name:'Map a place'}).waitFor();await op.getByRole('button',{name:'Map a place'}).click();await op.getByLabel('PLACE NAME').fill('Medical help');await op.getByLabel(/^TYPE/).selectOption('medical');await op.getByLabel('CURRENT OBSERVATION').selectOption('normal');await op.getByRole('button',{name:'Publish observation'}).click();await page.getByRole('button',{name:'Medical help medical · normal'}).waitFor({timeout:10000});
assert.equal((await api(root+'/scan',{pass:'wrong',direction:'entry'},room.staffToken)).status,404);
assert.equal((await api(root+'/zones',{name:'Invalid',lat:999,lng:10,kind:'gate',status:'normal'},room.staffToken)).status,400);
await page.goto(base+'/');await page.getByRole('link',{name:/Your live venue companion/}).waitFor();await page.screenshot({path:'checks/home-mobile.png',fullPage:true});
assert.deepEqual(errors,[]); console.log(JSON.stringify({passed:true,checks:['map renders','location consent and aggregation','location stop removes observation','private credentials omitted','staff-only updates','entry/exit count','duplicate scan rejected','closed destination blocks directions','cross-context updates','mobile no overflow','original homepage renders','no browser runtime exceptions'],room:room.code},null,2));await browser.close();
